### ISSUE TITLE
Failed to register local environment: Sharing environment failed.

### ISSUE THREAD

**Issue by DenisMtfl** [MicrosoftDocs/vsonline#255] opened 2019-12-12 15:13 UTC
Is there a log?

Windows 10 Pro
VS Code

**Comment by taiyosogawa** [comment] 2019-12-16 18:21
@DenisMtfl, thank you very much for reporting your experience - I'm sorry that self-hosted registration did not work properly. You can access some of the logs via the command palette with the command **VS Online: Export Logs**.

It is possible that you are encountering the same problem as #258. Do you have spaces in the file path to the workspace you are registering?

**Comment by hson89** [comment] 2020-01-02 00:05
I have just had this issue for the last few days too. Below is the log in my environment
> Command [Register Local Environment]: Register Local Environment Failure: vso login failed: 'C:\Users\admin\AppData\Local\Temp/vso/VSOAgent_win_3320984/vso' is not recognized as an internal or external command,
operable program or batch file.

I tried to look at that folder and didn't see any vso executable file

**Comment by jkeech** [comment] 2020-01-02 00:28
@hson89, it sounds like the cached agent folder is corrupted. Can you delete the entire %temp%\vso folder and then run the register command again? It will redownload the agent if the folder does not exist. In the future, we can add a better consistency check on the downloaded agent so that it will auto-recover during the next registration if the agent download is corrupted/deleted, but for now you’d have to manually remove the folder to force it to download again.

**Comment by hson89** [comment] 2020-01-02 01:46
@jkeech : Thanks for your advice. It works! :)

**Comment by mhelmydiab** [comment] 2020-01-12 14:43
Hello, im facing a similar issue but deleting the vso folder didnt solve it. Here is the log. Thnax

[2020-01-12 13:08:08.698 serverSharing V] > serverSharing.browseSharingStarted: 
[2020-01-12 13:08:08.699 serverSharing V] > serverSharing.startSharing() succeeded
[2020-01-12 13:08:08.724 terminal V] < terminal.getRunningTerminals()
[2020-01-12 13:08:08.837 terminal V] > terminal.getRunningTerminals() succeeded
[2020-01-12 13:08:10.659 streamManager V] < streamManager.getStream()
[2020-01-12 13:08:10.662 streamManager V] < streamManager.getStream()
[2020-01-12 13:08:10.805 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:08:10.806 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:08:23.263 streamManager V] < streamManager.getStream()
[2020-01-12 13:08:23.377 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:08:23.525 streamManager V] < streamManager.getStream()
[2020-01-12 13:08:23.639 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:09:04.525 streamManager V] < streamManager.getStream()
[2020-01-12 13:09:04.633 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:09:04.795 streamManager V] < streamManager.getStream()
[2020-01-12 13:09:05.294 streamManager V] > streamManager.getStream() succeeded
[2020-01-12 13:11:54.069 Command:u I] Decorator starting: l
[2020-01-12 13:11:54.069 Command:u I] Decorator starting: a
[2020-01-12 13:11:56.146 Command:u E] Command [Register Local Environment]: Register Local Environment By Design Failure: Self-hosted environments not yet supported on vsonline. (2075ms)
[2020-01-12 13:11:56.146 Command:u I] Decorator finishing: a. Duration: 2076ms (1 + 2075)
[2020-01-12 13:15:17.006 Command:d I] Decorator starting: l
[2020-01-12 13:15:17.006 Command:d I] Decorator starting: a
[2020-01-12 13:15:17.017 Command:d I] Command [Disconnect]: Disconnect Success (8ms)
[2020-01-12 13:15:17.018 Command:d I] Decorator finishing: a. Duration: 5ms (3 + 2)
[2020-01-12 13:15:17.018 Command:d I] Decorator finishing: l. Duration: 0ms (0 + 0)

**Comment by taiyosogawa** [comment] 2020-01-12 16:29
Thanks for the detailed info. Based on the logs, it looks like you're
trying to register while already connected to a self-hosted environment (or
other remote development scenario). Unfortunately, this is not yet
supported.

If you're trying to register the machine you're working on, then try
disconnecting before running the register command. Let me know whether that
works or if you think the issue you're seeing is different.

**Comment by Fireant456** [comment] 2020-01-20 17:37
Hello I am having a similar issue in #258 deleting the VSO folder did not do the trick and the logs seem rather unhelpful...

**Comment by taiyosogawa** [comment] 2020-01-20 17:51
Hi @Fireant456, I'm sorry about the issue that you're experiencing.

- Could you help me understand the similarities you see with #258? (Do you have a space in your workspace path?)
- What version of the Visual Studio Online extension are you using?

**Comment by Fireant456** [comment] 2020-01-20 17:55
no my workspace path is as follows `S:\GLG\GLG-Workspace-secondary.code-workspace`

**Comment by Fireant456** [comment] 2020-01-20 17:56
VS Online Version: 1.0.1507
VS Code Version: 1.41.1

**Comment by Fireant456** [comment] 2020-01-20 18:08
Sorry @taiyosogawa I meant #284 not #258

**Comment by taiyosogawa** [comment] 2020-01-20 18:28
Ah, I see - thanks for clarifying @Fireant456. Let's continue our conversation over there.

@DenisMtfl, let me know if you have any additional information to help us troubleshoot the issue you're experiencing.

**Comment by taiyosogawa** [comment] 2020-04-10 17:51
We have made several bug fixes since this particular issue, so I am going to close this out to keep things organized. If you are still experiencing this issue or another one, please don't hesitate to re-open with details or file a new issue.

**Closed by taiyosogawa** 2020-04-10 17:51 UTC
Labels: area: self-hosting, bug
