### ISSUE TITLE
Cannot sign-in Visual Studio Online from vscode after successfully login in broswer (Firefox + CentOS)

### ISSUE THREAD

**Issue by dancebean** [MicrosoftDocs/vsonline#265] opened 2019-12-21 02:56 UTC
I want to sign-in Visual Studio Online from within Visual Studio Code. After successfully login Microsoft account (Azure-subscribed) in broswer (Firefox + CentOS), and click continue button, it won't redirect me back to the VSCode interface.

Is it possible to use the sign-in code approach, similar to what is used to login to the Azure account from VScode? (which I can successfully logged in.)

**Comment by fara-nak** [comment] 2020-01-08 23:50
thanks for reporting the issue. currently we don't support Firefoc, you can try Chrome or Edge Chromium.

**Comment by fara-nak** [comment] 2020-01-08 23:50
closing this bug as a duplicate of #34

**Closed by fara-nak** 2020-01-08 23:50 UTC
