### ISSUE TITLE
Can't Debug C++ Apps

### ISSUE THREAD

**Issue by nbarkhina** [MicrosoftDocs/vsonline#175] opened 2019-11-13 14:50 UTC
I'm using the browser based version of Visual Studio Online. I'm just trying to see if debugging works on a simple hello world cpp file.  when I try to debug I get this error -

&"warning: GDB: Failed to set controlling terminal: Operation not permitted\n"

I have GDB installed and the VS Code C++ Extension. When I try the exact same project on a regular Linux machine debugging works. Here is my project if you want to see what my launch.json and tasks.json looks like - 

https://github.com/nbarkhina/CPlusHelloWOrld

Thanks

**Comment by edgonmsft** [comment] 2019-11-13 17:24
Hi Neil!

Thanks for the information!

This one gets fixed with the same changed referenced in [140](https://github.com/MicrosoftDocs/vsonline/issues/140), we'll continue the follow up there.

The change will be in the next release in a couple of days.

**Closed** 2019-11-13 17:25 UTC
Labels: area: kitchensink, enhancement

**Comment by edgonmsft** [comment] 2019-11-16 00:23
As an FYI the fix went out today. If you create a new environment you should be able to debug it.

**Comment by nbarkhina** [comment] 2019-11-16 01:23
it's still giving the same error. maybe it hasn't pushed out everywhere yet?

![image](https://user-images.githubusercontent.com/10982154/68985610-bbed0780-07e5-11ea-9def-04e7d065a8fa.png)

**Comment by jkeech** [comment] 2019-11-16 01:35
@nbarkhina, I'm not able to reproduce this with your sample repo. After installing GDB and the C++ extension, I can set a breakpoint and hit it when debugging via F5.

![image](https://user-images.githubusercontent.com/746020/68985784-fe0a4f00-07cd-11ea-897b-0a863b7bf4ea.png)

Did you create a new environment, or just restart the old one? In this case, it will only work for newly created environments because the fix was to modify the parameters that were used to create the environment's container.

**Comment by nbarkhina** [comment] 2019-11-16 13:10
I tried it on the old environment. I will try creating a new environment and give it a test. Thanks

**Comment by nbarkhina** [comment] 2019-11-16 14:30
Yes it works now in a new environment, thanks!

**Comment by jkeech** [comment] 2019-11-16 15:29
Great! Thanks for confirming.
