### ISSUE TITLE
Self-host: reconnect to previous session shells?

### ISSUE THREAD

**Issue by fpintos** [MicrosoftDocs/vsonline#332] opened 2020-03-05 07:27 UTC
Would it be possible to reconnect to a previous session shell when VSCode disconnects from a remote session and we need to reload?

Here's my scenario:
- I connect to my remote self-hosted devbox using my local vscode instance.
- on the integrated terminal, I start a long running process, such as a big build or a react app which I'll be working on.
- eventually, for whatever reason, vscode disconnects - it can be that I left the laptop unattended and it went to sleep or maybe I'm just moving around and switching wifi connections, who know.
- if enough time passes, when we reconnect, we end up with some brand new shell session and the previous long running process is gone from the remote host.
- so now I have to start the long process all over again.

Compare this to a Remote Desktop session, where all the processes remain active. Granted that it solves different cases, but if I want to ditch Remote Desktop in favor of just VSOnline then it would be great if my remote processes started from my local vscode could remain running even on the event of long disconnects.

Any chance we can tell a self-hosted environment to keep running the processes and reconnect to their output? If that already exists, can you point me to the docs?

Thanks

**Comment by jkeech** [comment] 2020-03-05 19:16
@fpintos, it's not possible today due to VS Code's remote architecture. The extension host on the remote side only stays alive as long as it has a renderer (client) connected. When the extension host exits, any terminal spun up through the host is also killed.

I understand the desire for this behavior though. It's something we will follow up with the VS Code team about to see what the options are. The current behavior should be the same for self-hosted VSO environments, managed VSO environments, and VS Code remote SSH/containers/etc.

**Comment by bennycornelissen** [comment] 2020-03-05 19:24
As an intermediate solution, would it be possible to run tmux _inside_ the terminal and run the commands in there?

**Comment by jkeech** [comment] 2020-03-06 00:37
@bennycornelissen, thanks for the suggestion! I hadn't tried tmux as a way to solve this, but it does work and is a good workaround in this case. If you are using of course the tmux'd shells won't survive a reboot (or suspend/resume in the managed environment case), but it will survive a VS Code reload or client-side disconnect.

**Comment by lostintangent** [comment] 2020-03-21 16:22
This is actually a duplicate of #239, so I’m going to close this issue, so we can consolidate the discussion in one place 👍

**Closed by lostintangent** 2020-03-21 16:22 UTC
