### ISSUE TITLE
Add note that ADO can be used as connected repository

### ISSUE THREAD

**Issue by profexorgeek** [MicrosoftDocs/vsonline#563] opened 2020-06-04 14:15 UTC
@abuchholtzau and @gregvanl  - Oliver Doerr recommended that we add a note to this page:

> https://github.com/MicrosoftDocs/vsonline/blob/master/vs-online/reference/repository.md

...indicating that it is possible to use Azure DevOps as a connected Repository.

**Comment by abuchholtzau** [comment] 2020-06-04 14:20
Yup we've been meaning to add that! I believe Nik created an issue for it a couple of weeks ago as well.

**Comment by gregvanl** [comment] 2020-06-04 14:27
Looks like duplicate of https://github.com/MicrosoftDocs/vsonline/issues/494

**Comment by OliCSADoerr** [comment] 2020-06-04 14:28
Great to see the light speed response! Looking forward to the updated documentation.

**Comment by gregvanl** [comment] 2020-07-10 21:41
Closing as duplicate

**Closed** 2020-07-10 21:41 UTC
Labels: doc-bug, duplicate
