### ISSUE TITLE
Need a way to switch between tenants when creating environments

### ISSUE THREAD

**Issue by artisticcheese** [MicrosoftDocs/vsonline#154] opened 2019-11-10 18:27 UTC
Right now if your account is part of several tenants, subscriptions are only showing up from random tenant instead of giving option to choose which tenant you want to show subscription for (like Azure portal allows one to do).
If you try to create environment from VS Code plugin though all subscriptions from all tenants are shown, so it works as expected from plugin.

**Comment by fara-nak** [comment] 2019-11-11 16:40
Hi @artisticcheese thanks for reporting this issue. I'm going to close this bug as a duplicate of [this one](https://github.com/MicrosoftDocs/vsonline/issues/39).

**Closed by fara-nak** 2019-11-11 16:40 UTC
