### ISSUE TITLE
devcontainer.json - "overrideCommand: false" error

### ISSUE THREAD

**Issue by extravio** [MicrosoftDocs/vsonline#291] opened 2020-01-28 03:42 UTC
I'm trying to set up a LAMP stack on VS Online using the example on "vscode-remote-try-php" 
https://github.com/microsoft/vscode-remote-try-php/tree/master/.devcontainer

I replaced the php:7-cli image by the php/7.3-apache image (https://hub.docker.com/_/php)
the container starts and I can connect to it.
However I need to start the apache service manually.

If I set `"overrideCommand": false` in the devcontainer.json as suggested here:
https://github.com/microsoft/vscode-dev-containers/issues/219
I get the following error:
_Failed to copy the VSOnline Agent to the custom container_

The output on the command line is:
```
COMMAND: docker exec -u root vsonline_3eb29cf4-5743-4c34-804a-8ca4818bea3d mkdir -p /.vsonline/bin
docker process exited with exit code 137
```

Thanks.

**Comment by edgonmsft** [comment] 2020-01-28 05:20
Hi @extravio! Thanks for reporting this issue. 

I saw that you posted a similar issue in vscode-devcontainers. I just wanted to get more context on the issue you are having. Do you have an example repository with the changes you made you can point me to? In addition can you post the rest of the create logs? I'm mainly interested in the docker create command.

Let me make some tests with the image you reference and get back to you. 

From what I can see it looks like the container is no longer running by the time we run that command witch would mean the original image or your docker file do not have a run command.

**Comment by extravio** [comment] 2020-01-28 20:25
Hi @edgonmsft,
The repo I'm using is the folllowing: https://github.com/extravio/ss4-azure
It's a bit messy, sorry :)

On this commit:
https://github.com/extravio/ss4-azure/tree/6e90fe40c79fa766522cb0901a799c50db50d73a
I used the code found in "vscode-remote-try-php".
The only change is in theDockerfile: I replaced the base image php:7-cli by php:7.3-apache.

The environment gets created successfully (logs below).

```
[...]
(*) Success!

docker process exited with exit code 0
COMMAND: docker exec -u root vsonline_8165f987-f91d-44db-907c-4b0e2bfdf30d chown -R vscode /.vsonline/bin
docker process exited with exit code 0
COMMAND: docker exec -u root vsonline_8165f987-f91d-44db-907c-4b0e2bfdf30d chown -R vscode /home/vscode
docker process exited with exit code 0
Starting environment...
Terminal exited. Press any key to close it
```

However, apache is not running by default:
![php7-apache](https://user-images.githubusercontent.com/1171158/73301939-a762cc00-4278-11ea-914c-859a4569e39d.PNG)

I can start apache manually and everything is working correctly.

If I add the ` "overrideCommand": false` entry in devcontainer.json however, I get the error mentioned above.
commit:
https://github.com/extravio/ss4-azure/tree/19a183d7348158645f7ec58bb3d87c1d2ec64903

Here are the logs:
```
[...]
Removing intermediate container 7fed28373b6c
Step 7/7 : ENV DEBIAN_FRONTEND=
 ---> Running in 22fa58c49f85
 ---> 84acd8ab0df4
Successfully built 84acd8ab0df4
Removing intermediate container 22fa58c49f85
Successfully tagged cloudenvimage:latest
docker process exited with exit code 0
COMMAND: docker create --restart=on-failure:10 -v /root/.vsonline/.vsoshared:/home/vscode/.vsonline/.vsoshared -v /mnt/cloudenvdata/containerlogs:/tmp/VSFeedbackVSRTCLogs --name vsonline_caab2709-a629-4819-9526-27b63419cc49 --user vscode --label Type=vsonline --label StartCLI=True --label User=vscode cloudenvimage 
5a0ef9b0283d8c99dee58c82263ff738bf8ee6fd1588077ab6b269d73aabeacc
docker process exited with exit code 0
COMMAND: docker start vsonline_caab2709-a629-4819-9526-27b63419cc49
vsonline_caab2709-a629-4819-9526-27b63419cc49
docker process exited with exit code 0
COMMAND: docker exec -u root vsonline_caab2709-a629-4819-9526-27b63419cc49 mkdir -p /.vsonline/bin
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "process_linux.go:91: executing setns process caused \"exit status 21\"": unknown
docker process exited with exit code 126
```

![error](https://user-images.githubusercontent.com/1171158/73302218-1d673300-4279-11ea-8704-0f0aec8f28f6.PNG)

Let me know if you need more info.

**Comment by edgonmsft** [comment] 2020-01-28 21:37
Hi @extravio! 

Thanks a lot for the repository. I've made a copy of the files you referenced and made some tests.

The container is starting and stopping with an error from apache: 
**AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
(13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs**

Since apache is the run command, if it fails, the container dies. I assume that there is some missing configuration or maybe the user needed to run apache correctly is different.

Perhaps you can set the container user differently.

I will be working on improving the output in this cases so that it is easier to debug.

**Comment by extravio** [comment] 2020-01-28 22:26
Hi @edgonmsft, 

The message about the Servername is just a warning and should not prevent the container from starting. When starting apache manually in the first case, the same message is displayed but the server starts successfully (as in the first screenshot).

I will add some configuration to avoid this warning and re-test to see if that's the problem. Thanks.

**Comment by edgonmsft** [comment] 2020-01-28 22:28
Ok @extravio, I think the issue is not being able to bind to the address or the logs related error. If your changes work please let me know.

**Comment by extravio** [comment] 2020-01-29 02:09
Hi @edgonmsft,
I think the problem was that Apache is running by default on port 80 and this port is used during the creation of the environment it seems.
I changed the apache configuration to use port 8080
https://github.com/extravio/ss4-azure/commit/bf128b0b3190906fb21564cbc6ddfc0a1df59823
and it's working now.
Cheers!

**Comment by extravio** [comment] 2020-01-30 04:10
Hi @edgonmsft,

How were you able to see the following output?
Is there a setting/flag to get extra debugging info?

> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.17.0.2. Set the 'ServerName' directive globally to suppress this message
> (13)Permission denied: AH00072: make_sock: could not bind to address 0.0.0.0:80
> no listening sockets available, shutting down
> AH00015: Unable to open logs

I get the same error when I tried to enable SSL in my container.

**Comment by edgonmsft** [comment] 2020-01-30 17:16
Hi @extravio,

That's the reason I'm keeping this issue open, at this moment there is no way to get this output, I'll be adding code to show it when the container gets created but fails afterwards. Its the output of the docker logs command.

**Comment by jkeech** [comment] 2020-02-28 18:17
If the container fails to start, we now print the logs from the container execution to the terminal that is rendered. Closing this issue.

**Closed by jkeech** 2020-02-28 18:17 UTC
