### ISSUE TITLE
Port forward causes HTTP 504 error with dotnet core 3.1 web app

### ISSUE THREAD

**Issue by adhurwit** [MicrosoftDocs/vsonline#328] opened 2020-03-03 18:32 UTC
When I run a new web app with dotnet core 3.1 and then try to port forward, I get a HTTP 504 error.

**Comment by lostintangent** [comment] 2020-03-21 16:37
Thanks for reporting this! This is a duplicate of #123, so I’m going to close this in order to consolidate the conversation. Thanks!

**Closed by lostintangent** 2020-03-21 16:37 UTC
