### ISSUE TITLE
Authentication failed cloning a private Github repo

### ISSUE THREAD

**Issue by connor4312** [MicrosoftDocs/vsonline#306] opened 2020-02-18 00:55 UTC
I tried to clone a private repo, but ran into some issues. This is the output from the VS Online terminal. Running that latest 1.43.0 insiders.

```
OPERATION_ID=4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377 /.vsonline/bin/vso exec git config --global user.name "Connor Peet"
vsonline:~$ OPERATION_ID=4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377 /.vsonline/bin/vso exec git config --global user.name "Connor Peet"
[2020-02-18 00:50:52.004 CLI I] vso v1.0.1605.52138 (pid: 155)
[VS Online][4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377] Process finished successfully.
vsonline:~$ OPERATION_ID=1957bcfe-088b-47e5-98d9-9980f8c2086f /.vsonline/bin/vso exec git config --global user.email "connor@xbox.com"
[2020-02-18 00:50:52.905 CLI I] vso v1.0.1605.52138 (pid: 173)
[VS Online][1957bcfe-088b-47e5-98d9-9980f8c2086f] Process finished successfully.
vsonline:~$ OPERATION_ID=d03208c4-7549-4aed-9519-bae904b8c357 /.vsonline/bin/vso exec git ls-remote https://github.com/connor4312/mopidy-azure.git heads/master
[2020-02-18 00:50:53.695 CLI I] vso v1.0.1605.52138 (pid: 190)
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[VS Online][d03208c4-7549-4aed-9519-bae904b8c357] Process exited with non - zero result (128).
vsonline:~$ OPERATION_ID=3232dac8-6bab-4b9a-9dcd-360a71cb6c98 /.vsonline/bin/vso exec git ls-remote https://github.com/connor4312/mopidy-azure.git heads/master
[2020-02-18 00:51:38.584 CLI I] vso v1.0.1605.52138 (pid: 338)
OPERATION_ID=4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377 /.vsonline/bin/vso exec git config --global user.name "Connor Peet"
vsonline:~$ OPERATION_ID=4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377 /.vsonline/bin/vso exec git config --global user.name "Connor Peet"
[2020-02-18 00:50:52.004 CLI I] vso v1.0.1605.52138 (pid: 155)
[VS Online][4e2dcd3c-ad0d-44c7-a628-c0c1edb4e377] Process finished successfully.
vsonline:~$ OPERATION_ID=1957bcfe-088b-47e5-98d9-9980f8c2086f /.vsonline/bin/vso exec git config --global user.email "connor@xbox.com"
[2020-02-18 00:50:52.905 CLI I] vso v1.0.1605.52138 (pid: 173)
[VS Online][1957bcfe-088b-47e5-98d9-9980f8c2086f] Process finished successfully.
vsonline:~$ OPERATION_ID=d03208c4-7549-4aed-9519-bae904b8c357 /.vsonline/bin/vso exec git ls-remote https://github.com/connor4312/mopidy-azure.git heads/master
[2020-02-18 00:50:53.695 CLI I] vso v1.0.1605.52138 (pid: 190)
fatal: could not read Username for 'https://github.com': terminal prompts disabled
[VS Online][d03208c4-7549-4aed-9519-bae904b8c357] Process exited with non - zero result (128).
vsonline:~$ OPERATION_ID=3232dac8-6bab-4b9a-9dcd-360a71cb6c98 /.vsonline/bin/vso exec git ls-remote https://github.com/connor4312/mopidy-azure.git heads/master
[2020-02-18 00:51:38.584 CLI I] vso v1.0.1605.52138 (pid: 338)
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/connor4312/mopidy-azure.git/'
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/connor4312/mopidy-azure.git/'
[VS Online][3232dac8-6bab-4b9a-9dcd-360a71cb6c98] Process exited with non - zero result (128).
[VS Online][3232dac8-6bab-4b9a-9dcd-360a71cb6c98] Process exited with non - zero result (128).
```

**Comment by lostintangent** [comment] 2020-03-01 17:48
@connor4312 Thanks for reporting this! Out of curiosity: do you typically authenticate with GitHub via SSH? 

@edgonmsft Have we seen this issue before? This line seems to indicate that he wasn't authenticated with GitHub, and we weren't able to prompt him for credentials?

```shell
fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

**Comment by edgonmsft** [comment] 2020-03-01 18:31
@lostintangent The line you mention appears for two reasons. It means the credential proxy failed, meaning we couldn't get credentials from the users machine or browser, and we disable terminal prompts to prevent the configuration process from hanging.

@connor4312 From the output you show, can you tell me the following?
- To confirm, this was from VS Code desktop?
- Are you able to clone/push this repo locally?
- Do you have multiple github users/profiles? Its possible we are getting credentials for a different user and thats why they are failing, although from the output it appears that the credentials we are getting are invalid. One posibility is to clear them from Credential Manager or Keychain and login locally again.

Thanks!

**Comment by connor4312** [comment] 2020-03-02 15:45
- I triggered it through the web portal, then tried to open it on VS Code desktop.
 - I am able to push/clone locally using my SSH key.
 - Just one user using an SSH key. The key isn't installed in any credential manager on windows as far as I know, so I don't think it would be able to pull that info (the correct credentials) from there.

**Comment by edgonmsft** [comment] 2020-03-02 17:43
Ok thanks! For now we don't support SSH keys so that is the reason you are having this issue. Its on the roadmap along with some other things.

We are tracking that work on: #311

**Comment by lostintangent** [comment] 2020-04-04 19:28
Closing this as a duplicate of #311, so that we can track progress in a single place 👍

**Closed by lostintangent** 2020-04-04 19:28 UTC
Labels: area: github, area:customization, bug
