### ISSUE TITLE
Confusion about devcontainer

### ISSUE THREAD

**Issue by fenixsolorzano** [MicrosoftDocs/vsonline#369] opened 2020-03-29 21:46 UTC
Before knowing about VS Online I was using devcontainers for setting up my whole project without having to run docker commands repeatedly; I'm not sure if I'm doing it wrong but now I understand that VS Online `devcontainer.json` will setup the development environment, in my case I had my project configured with `docker-compose.yml` files so my current setup with VS Online is:

- Use `devcontainer.json` to setup development environment needs to work in my project.
  - Dockerfile with node.js, sudo, git, etc for example
- Use `postCreateCommand` at `devcontainer.json` to build and run my app with docker-compose

By doing that I'm able to get my app running, but I'm unable to use Dev Container feature anymore because inside te dev environment I can't connect to the app container just to the dev container.

Questions
- Is that the right way to use VS Online? _(I mean running docker on docker)_
- How can I use past Dev Container feature along with VS Online _(which I believe it's an SSH connection)_?

### Update 1
After doing some research on issues I ended up in #334, the current behavior it's awkward, reloading the window worked to get vs code docker features but I'm still not able to connect to my app container

**Comment by jkeech** [comment] 2020-03-30 15:46
@fenixsolorzano, can you share the `devcontainer.json` file that you were using prior to using VS Online? We are working on adding built-in docker compose support for devcontainer.json and changing the user on the default image to be able to run docker commands without `sudo` as part of #40. I'm hoping that your scenario will be covered by those changes, but it would be great to confirm.

**Comment by lostintangent** [comment] 2020-04-04 19:14
I’m going to close this as a duplicate of #35 and #40, but please re-open it if these issues don’t properly account for your issue/request. Thanks!

**Closed by lostintangent** 2020-04-04 19:14 UTC
