### ISSUE TITLE
The Additional Views button is missing aligned

### ISSUE THREAD

**Issue by hologerry** [MicrosoftDocs/vsonline#112] opened 2019-11-07 08:37 UTC
<img width="227" alt="Screen Shot 2019-11-07 at 16 35 10" src="https://user-images.githubusercontent.com/11660168/68372985-d9cec280-017c-11ea-8eee-464bdd884dd7.png">

**Comment by egamma** [comment] 2019-11-09 16:15
I cannot reproduce this in VSO on Chrome. I'm not able to reproduce this in VS Code Web in the latest version of the VS Code insider

Version: 1.41.0-insider
Commit: 27cd33d891eb23e370b672e751be9fe8b3748ac1
Date: 2019-11-08T18:56:57.709Z
Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6)

// fyi @bpasero

**Comment by bpasero** [comment] 2019-11-10 14:42
@hologerry on what browser?

**Comment by egamma** [comment] 2019-11-10 15:22
@bpasero I can repro this in Chrome when using VS Online, but I cannot repro this in VS Code Web.

**Comment by bpasero** [comment] 2019-11-10 15:32
Yeah, a regression. Filed https://github.com/microsoft/vscode/issues/84419 on our end.

**Comment by bpasero** [comment] 2019-11-10 15:33
Btw this reproduces in VSCode stable too, unrelated to VSO.

**Comment by hologerry** [comment] 2019-11-10 15:33
I tried the VS Online on Chrome with the latest 1.40, this issue occurs.

**Comment by lostintangent** [comment] 2019-11-16 22:51
Closing this as external, per @bpasero’s comment 👍

**Closed by lostintangent** 2019-11-16 22:51 UTC
