### ISSUE TITLE
Could not connect to VSO from my vscode install

### ISSUE THREAD

**Issue by cartermp** [MicrosoftDocs/vsonline#209] opened 2019-11-22 16:43 UTC
I get the following notification when I attempt to connect to an online environment from my VSCode install:

<img width="468" alt="image" src="https://user-images.githubusercontent.com/6309070/69443758-e66a2380-0d03-11ea-9daa-dec5a60ad333.png">

However, I am signed in with my Azure account where I do have an environment.

<img width="190" alt="image" src="https://user-images.githubusercontent.com/6309070/69443812-04378880-0d04-11ea-95ce-448eb471b286.png">

When prompted to create a new environment, I get this error:

<img width="462" alt="image" src="https://user-images.githubusercontent.com/6309070/69443841-10bbe100-0d04-11ea-8d81-62b58c898d54.png">

But I signed in with my MS account to create the environment. I don't think I have a VSO account with my personal email address:

<img width="222" alt="image" src="https://user-images.githubusercontent.com/6309070/69443904-29c49200-0d04-11ea-9817-2ac744244b52.png">

**Comment by srivatsn** [comment] 2019-11-22 17:10
@jasongin  @legomushroom

**Comment by jkeech** [comment] 2019-11-22 17:12
@cartermp, there are two logins currently on the VS Code desktop client. The one in your second screenshot is the Azure extension. The error message in the third screenshot is the account used to sign into VSO in VS Code. The error message indicates that the two sign ins don't match. Can you try signing out of VSO in VS Code and then signing in again with the phcart@microsoft.com acocunt? In the command palette: "VS Online: Sign Out", then "VS Online: Sign In"

**Comment by cartermp** [comment] 2019-11-23 00:43
Thanks @jkeech - I signed out, but then had to restart VSCode because it didn't seem to sign me out (or maybe it did, but there was no notification). After opening it up again, I was prompted to sign in and I could then connect to my environment.

**Comment by jkeech** [comment] 2019-11-23 00:45
Glad to hear. It should have signed you out immediately without a restart, but I don't think there's a notification today. That's good feedback. I'm going to close this issue since the mismatched accounts issue is now resolved. I suspect this is also the root cause of #208 as well. If you were signed in with the wrong account in VS Code desktop, when it tried to connect to the environment after switching from the browser, it would not have found the environment. We also need better error notifications in this case. /cc @osortega.

**Closed by jkeech** 2019-11-23 00:45 UTC
