### ISSUE TITLE
button "open in vsonline"

### ISSUE THREAD

**Issue by renatoassis01** [MicrosoftDocs/vsonline#63] opened 2019-11-05 04:26 UTC
it would be nice to have an "open in vsonline" button to be added to the project readme

**Comment by plisy** [comment] 2019-11-05 05:19
We support a deep link feature where you can specify environment name and repository. Once someone navigates to that link, we'll pre-fill the creation form for them and they only need to click create.

Is that the experience you're looking for?

You can also follow issue #56 for documentation of this feature and issue #37 for deep link url samples.

**Comment by lostintangent** [comment] 2019-11-05 14:10
I'm going to close this as a duplicate of #37, which we're using to track the work to document our deep link feature. As part of that, we'll also document the "Open in VS Online" badge for project readmes. Thanks!

**Closed by lostintangent** 2019-11-05 14:10 UTC
