### ISSUE TITLE
Self-hosted registration fails with "Unrecognized option '--vso-uri'"

### ISSUE THREAD

**Issue by kyelewis** [MicrosoftDocs/vsonline#388] opened 2020-04-08 05:56 UTC
Using Visual Studio Code 1.43.2 and VS Online Extension 1.0.1968

Run "Register self-hosted environment.."
Expected: Registration continues.
Actual: Fails with the error "Register Self-hosted Environment: (Error 1) Unrecognized option '--vso-uri'"

**Comment by jkeech** [comment] 2020-04-08 05:58
Thanks for reporting. Closing as a duplicate of #387.

**Closed by jkeech** 2020-04-08 05:58 UTC
