### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by FranklinArdian** [MicrosoftDocs/vsonline#269] opened 2020-01-03 15:17 UTC
- Issue Type: `Performance`
- Extension Name: `vsonline`
- Extension Version: `1.0.1424`
- OS Version: `Windows_NT x64 10.0.18362`
- VSCode version: `1.41.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\WAWAN\ms-vsonline.vsonline-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by srivatsn** [comment] 2020-01-03 17:32
@FranklinArdian thanks for reporting this. Could you please attach the cpuprofile file mentioned above?

**Comment by jkeech** [comment] 2020-01-22 20:29
Closing this issue since we haven't received the CPU trace or been able to reproduce this. Please file a new issue if this happens again. Thanks!

**Closed by jkeech** 2020-01-22 20:29 UTC
Labels: status: info requested
