### ISSUE TITLE
Loading user settings.json from dotfiles

### ISSUE THREAD

**Issue by mchelen** [MicrosoftDocs/vsonline#289] opened 2020-01-24 21:48 UTC
Hi, I'm trying to load a custom a user setting from my dotfiles when using VSOnline through a browser.

If I put a `settings.json` in `/home/vsonline/.config/Code/User/settings.json` then the settings are not read.

If I open `settings.json` with `Preferences: Open Settings (JSON)` it gives me a file that does have an effect, but doesn't seem to exist anywhere on the filesystem. Doing a right click `Copy Path` shows the file as being `/User/settings.json` but there is no such directory.

The setting I am trying to define is:
```json
{
"terminal.integrated.shell.linux": "/bin/zsh"
}
```

Is there some place I can have my dotfiles write this setting? It's intended to be a user setting, not a project setting, which is the reason for not using `.devcontainer`.

**Comment by nikmd23** [comment] 2020-01-28 16:42
Good question @mchelen. Let me loop in @Chuxel, who might be able to help.

**Comment by Chuxel** [comment] 2020-01-28 17:34
User settings are persisted in the browser using indexDB so that they apply across environments like they would in local scenarios.

The settings property in devcontainer.json sets "machine" level settings (displayed as "Remote" in the settings editor).  It allows you to have something like a different runtime path in multiple environments when you connect to it from VS Code.  This takes president over user settings, so it would be the right one to use in this case.  This file is located at: `/home/vsonline/.vscode-remote/data/Machine/settings.json`

**Comment by nikmd23** [comment] 2020-01-28 23:37
Thanks @Chuxel! This would be good info to have added into our docs. I've tagged it as such so we can make sure we don't forget.

**Comment by jkeech** [comment] 2020-01-29 03:36
@Chuxel, I think VS Code’s upcoming settings sync service is the right mechanism for personalized VS Code settings to roam across environments instead of having dotfiles carry a settings.json file.

**Comment by Chuxel** [comment] 2020-01-29 18:41
@jkeech Agreed. Purely answering based on what seems to be a reasonable workaround in the near term rather than making a specific feedback for this particular scenario given the sync capabilities are not yet available.

**Comment by lostintangent** [comment] 2020-03-21 17:55
Per the discussion, I’m going to close this issue as a duplicate of #169, since that’s going to be our recommendation for syncing user settings 👍

**Closed by lostintangent** 2020-03-21 17:55 UTC
Labels: documentation
