### ISSUE TITLE
EnvironmentDetailsExplorer polls even when not logged into VSO and makes extension host crash

### ISSUE THREAD

**Issue by egamma** [MicrosoftDocs/vsonline#223] opened 2019-11-27 15:01 UTC
Issue Type: <b>Bug</b>

Running on VS Code insiders with the latest VSO extension.

I'm not logged into VSO, but the EnvironementDetailsExplorer polls eagerly as can be seen from the devtools console log:

![image](https://user-images.githubusercontent.com/172399/69734286-00a26800-112f-11ea-915b-566f77e03bc3.png)

In this state there also is a memory leak and the extension host crashes with an out of memory extension after a while.

I cannot reproduce this behavior when I'm logged in.

**Comment by smvanderweide** [comment] 2019-12-10 18:43
I have done some investigation, and it seems like we have seen similar behavior caused by an invalid token when  updating from a pre-launch version of the extension (see [#52](https://github.com/MicrosoftDocs/vsonline/issues/52)). Is that the context you were seeing this issue in? If you delete the the vscode account credentials stored in the keychain, does that fix the problem?

**Comment by egamma** [comment] 2019-12-11 08:03
>when updating from a pre-launch version of the extension (see #52). Is that the context you were seeing this issue in?

This could well be the context I have seen this. Once I've logged in again the problem went away.

Even if the problem went away there should be some protection against polling the service every couple of milliseconds.

**Comment by smvanderweide** [comment] 2019-12-19 18:21
I looked into what might be causing the polling and how to protect against it, and the current version of the extension already has these protections in place. I am also still unable to reproduce the issue with the current extension, so I assume the issue has been resolved by other changes to our authentication flow and am closing the issue. If you encounter the problem again, please feel free to reopen the issue and we will take another look.

**Closed by smvanderweide** 2019-12-19 18:21 UTC
Labels: area: vscode, bug
