### ISSUE TITLE
Support Docker server and Kubernetes

### ISSUE THREAD

**Issue by giggio** [MicrosoftDocs/vsonline#40] opened 2019-11-04 17:05 UTC
I'm on a Kubernetes project now, and without Docker and k8s support I can't work. I need this to be able to move to VSOnline. I need a docker host. I don't care how you implement it, but I need to be able to run `docker` and `kubectl`, and I need to be able to access web apps hosted on it, just like you do with port forwarding. It can be in the local host, on a remote server attached to my environment, I don't care.

**Comment by Pothulapati** [comment] 2019-11-05 14:25
@lostintangent Just used VS Online, Awesome product. Just worked.

But I work on projects that are built as containers, and ran into the same issue as `docker` was installing. It would be awesome if it could support docker in docker and, also full user previliges on the dev container (like a full vm instance). So, that I can install things like `minikube` , etc. 
Thanks :)

**Comment by chrfrenning** [comment] 2019-11-07 19:56
+1 on docker support. Specifying container images to download and load would help create isolated development environments, e.g. by running mongod/sqlserver or other app dependencies within the environment. Containers should load before the init script so that data e.g. can be loaded prior to the environment becoming ready.

Alternatively, support for a teardown script would allow me to init containers in ACI as the environment spins up, and take them down when the environment suspends/is killed.

**Comment by nikmd23** [comment] 2019-11-08 01:20
Good input @chrfrenning! I've also created https://github.com/MicrosoftDocs/vsonline/issues/121 to track your comment about teardown scripts

**Comment by FuriKuri** [comment] 2020-01-16 19:02
+1
I find VS Online awesome. But the missing docker support prevents me from using it regularly. In most projects I need a docker environment to simply start certain services on the local machine, like Redis or something like Nginx.

**Comment by jkeech** [comment] 2020-02-28 18:34
Docker is now supported in VSO and the docker client comes preinstalled on the latest base images. We don't have `kubectl` baked into the base image yet, but you should be able to install it separately or use a custom image as described at https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring.

I'll keep this issue open to track supporting `kubectl` in the base image.

**Comment by nikmd23** [comment] 2020-02-28 21:40
@bradygaster - I wanted to make sure you saw [this update](https://github.com/MicrosoftDocs/vsonline/issues/40#issuecomment-592665589). I think that will be very useful for you. 😁

**Comment by giggio** [comment] 2020-02-29 00:01
@jkeech do you mean Docker server (a Docker host) or just the client?

**Comment by jkeech** [comment] 2020-02-29 00:27
@giggio - both. The docker client is installed in the base image, but we wire it up by default to a docker server that's running on the same VM. Of course you could point the client to a different docker server if you don't want the local one.

The local docker setup is following the [docker-outside-of-docker](http://blog.teracy.com/2017/09/11/how-to-use-docker-in-docker-dind-and-docker-outside-of-docker-dood-for-local-ci-testing/) model, so any containers you create will actually be sibling containers of the main environment container. The main downside of this is that you also have the power to stop the environment container which would kick you out of the environment until you restart it.

**Comment by giggio** [comment] 2020-02-29 00:41
This looks good, I'll try it out. Will the VM survive after a restart, or do we risk booting into a different VM on a restart (or other event)? I ask because the Docker Host would change if the VM changes.

**Comment by jkeech** [comment] 2020-02-29 00:42
@giggio, On environment restart you always get a fresh VM. But all of the docker layers and containers will be migrated to a new host as well, so you shouldn't lose any containers across restarts. You would just find them stopped and have to start them again.

**Comment by gorzell** [comment] 2020-02-29 13:02
Perhaps I have missed a step, but this still doesn't work with the VSCode Docker extension. I am guessing this is either permissions related (it doesn't work in the default terminal either), or perhaps where the extension is running?

My experience has been that you get permission denied when trying to access the unix socket, unless you sudo (given Docker's fondness for `root` this isn't entirely surprising). Is it up to us to setup the correct permissions within our Dockerfiles (not sure this is even possible since the socket is mounted read-only), or is that something that can be mapped in from the VM and handled at boot time? It may require some combination of the two in order to get the UIDs/GIDs to line up?

**Comment by jkeech** [comment] 2020-02-29 15:29
@gorzell. You’re right — you have to run sudo first. It’s intentional that the default image does not run as root, and in the case of docker, it also helps prevent you from stopping the main environment container accidentally. If you want to run the environment as root instead of having to elevate with sudo, you can use a devcontainer.json file in your repo to set the containerUser to root (and/or provide a custom image): https://code.visualstudio.com/docs/remote/containers-advanced.

**Comment by gorzell** [comment] 2020-03-01 13:00
Thanks. I will go down the path, although it is a bit sad that the extension won't work with the default containers then.

**Comment by lostintangent** [comment] 2020-03-01 17:53
I think we should look into how to make the VS Code Docker extension work out-of-the-box. Otherwise, we're not properly virtualizing the desktop experience in the cloud.

@chrisdias @fiveisprime Who is the right person to connect with on getting VSO working with the Docker extension, now that VSO supports managing Docker containers?

**Comment by fiveisprime** [comment] 2020-03-01 19:56
@BigMorty is the contact for the Docker extension.

**Comment by karolz-ms** [comment] 2020-03-06 01:05
@jkeech @lostintangent I am a member of the VS Code Docker extension team. 

Could you elaborate what would you want the extension to do differently in VS Online environment? FYI our current guidance is basically https://docs.docker.com/install/linux/linux-postinstall/#manage-docker-as-a-non-root-user

I assume this issue would be solved by running Docker in [rootless mode](https://docs.docker.com/engine/security/rootless/)--is that an option?

**Comment by jkeech** [comment] 2020-03-06 01:08
@karolz-ms, @edgonmsft is looking at doing just that -- adding the vsonline user id in the default base image to the docker group on the host so that it can run docker without specifying sudo. This is a bit riskier since it makes it easier to kill the environment container without explicitly elevating, but it's probably a reasonable tradeoff. There's nothing needed on the VS Code or Docker extension side to make this work.

**Comment by karolz-ms** [comment] 2020-03-06 01:16
OK great! In case you have any other questions re Docker extension, @BigMorty and myself are here to help.

**Comment by lostintangent** [comment] 2020-03-06 01:48
@jkeech Thanks for the update! This sounds great 👍

**Comment by BigMorty** [comment] 2020-03-06 04:07
Yes, please keep us posted on your progress!

**Comment by ItsWendell** [comment] 2020-03-17 13:08
I'm having issues using docker-compose / docker within Visual Studio Code Online. I'm using a default medium environment with 8GB of memory. Docker and docker-compose both work with when I run them as 'sudo', the problem is that I can't forward ports in Visual Studio Code Online that are created using docker-compose. Any idea how to solve this?

**Comment by bharatari** [comment] 2020-03-19 16:25
Possibly a related issue to @ItsWendell, I use docker-compose to spin up dependencies like Postgres and Redis so they're available on localhost within my dev environment. However, on a cloud-hosted VS Online environment, it looks like docker-compose containers don't expose their ports within the dev container. That is to say, after running `docker-compose up` and even with the following port configuration in `docker-compose.yml` I can't access Redis at redis://localhost:6379 within the dev environment as I would expect:

```
  redis:
    image: redis:5-alpine
    ports:
      - 6379:6379
```
I'm assuming this is because these containers are run using the docker-outside-of-docker model so I'm assuming the ports are being exposed to the actual host VM instead. Is there a way to get these ports exposed to the dev container in a manner consistent with how docker-compose would work on any other dev machine?

**Comment by karolz-ms** [comment] 2020-03-19 16:58
I have never tried it myself, but how about creating a Docker network, adding your dev environment container to it, then use the same network to launch your services under development?

It is not exactly the same as when your dev machine is not a container and is running Docker engine, but at least your dev container and the service containers should be able to communicate directly

**Comment by jkeech** [comment] 2020-03-19 17:54
@bharatari, @ItsWendell The ports should be visible once we implement #314 to run the containers with host networking enabled.

Until host networking is implemented, you have to go over the default docker networking setup, which exposes the sibling containers over a separate private IP address, which you can try from the terminal.

Example starting nginx:
```bash
vsonline:~/workspace$ sudo docker run -d nginx
e51aecf8c2fcc9cde6cb79b1eab034fcf303a868462f20d68bc81bf2d79f988a
vsonline:~/workspace$ sudo docker inspect e51aecf8c2fcc9cde6cb79b1eab034fcf303a868462f20d68bc81bf2d79f988a | grep IPAddress
            "SecondaryIPAddresses": null,
            "IPAddress": "172.17.0.3",
                    "IPAddress": "172.17.0.3",
vsonline:~/workspace$ curl 172.17.0.3
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>

**Comment by bradygaster** [comment] 2020-03-27 22:43
Quick update for folks on the cloud-native side of this. I worked with @squillace and @itowlson on an [opportunity in the Kubernetes extension for VS Code](https://github.com/Azure/vscode-kubernetes-tools/issues/715) that streamlines the ability for a K8S dev to add clusters to their dev environment. Previously, there was a small setup that'd need to take place that I'd automated in a bash script, but since they've fixed it things are way more streamlined now. If you'd like to try out a use-case of this, see my sample repo which has a simple [web, queue, worker](https://github.com/bradygaster/LongRuningProcessMonitor) scenario that's deployed to AKS. 

One thing to point out here after chatting with @abuchholtzau earlier who asked me to provide an update here. I'm still noticing the same behavior @timheuer reported in which the extensions "aren't there until I F5." No matter what, I **must** refresh my browser. I've waited 2 minutes, 5 minutes, a day, after creating the environment and going into it the first time, and every single time, it's consistent - the extensions I have in my `devcontainer.json` file aren't there until I hard-refresh the browser. This was my favorite aspect of this scenario, that extensions are "just there." Is there an issue on deck to resolve this?

**Comment by fenixsolorzano** [comment] 2020-03-29 17:49
Is there any example on how to use `docker-compose` to setup the containers of a project inside vsonline? I'm trying to use my dev container just as I do in my local machine (similar to @ItsWendell)

**Comment by fenixsolorzano** [comment] 2020-03-29 21:54
> @giggio - both. The docker client is installed in the base image, but we wire it up by default to a docker server that's running on the same VM. Of course you could point the client to a different docker server if you don't want the local one.
> 
> The local docker setup is following the [docker-outside-of-docker](http://blog.teracy.com/2017/09/11/how-to-use-docker-in-docker-dind-and-docker-outside-of-docker-dood-for-local-ci-testing/) model, so any containers you create will actually be sibling containers of the main environment container. The main downside of this is that you also have the power to stop the environment container which would kick you out of the environment until you restart it.

You should add this to the docs specs, it was crucial to me to understand this in order to mount my dev env

**Comment by jkeech** [comment] 2020-05-18 15:34
Both docker and kubernetes support has landed! :rocket: The default image ships with both the `docker` and `kubectl` clients, and the docker daemon is configured so you can spin up and manage containers locally on the host. Try it out and if you hit any problems, please open up another issue. Thanks!

**Closed by jkeech** 2020-05-18 15:34 UTC
Labels: area: extensions, enhancement
