### ISSUE TITLE
Building a new codespace from git fails when trying to build container

### ISSUE THREAD

**Issue by danecreekphotography** [MicrosoftDocs/vsonline#534] opened 2020-05-24 01:19 UTC
To reproduce:

1. Create a new codespace pointing to an existing git repo

Result: It fails
Expected result: It works

As far as I can tell this appears to be a typo in the build script Codespaces uses after pulling a git repo. It looks like there is a space missing in the `docker-compose` command line that's run to try and start building the containers from the repo:

```
COMMAND: docker-compose -f ..\docker-compose.yaml-f docker-compose.yml config --services
No such command: docker_compose.yml
  version            Show the Docker-Compose version information

  up                 Create and start containers
Commands:
  unpause            Unpause services
  build              Build or rebuild services
  top                Display the running processes
  stop               Stop services
  start              Start services
  scale              Set number of containers for a service
  run                Run a one-off command
  rm                 Remove stopped containers
  restart            Restart services
  push               Push service images
  pull               Pull service images
  ps                 List containers
  port               Print the public port for a port binding
  pause              Pause services
  logs               View output from containers
  kill               Kill containers
  images             List images
  help               Get help on a command
  exec               Execute a command in a running container
  events             Receive real time events from containers
  down               Stop and remove containers, networks, images, and volumes
  create             Create services
  config             Validate and view the Compose file
docker-compose process exited with exit code 1
Error inspecting docker-compose file for services. Please check your docker-compose file for issues.
```

**Comment by danecreekphotography** [comment] 2020-05-24 02:44
Adding more details after a Twitter convo: this is because I'm using multiple docker-compose.yml files:

```
"dockerComposeFile": ["..\\docker-compose.yaml", "docker-compose.yml"],
```
(As an aside, this also will fail because the backslashes are no bueno. VSCode should pre-populate with forward slashes...)

**Comment by edgonmsft** [comment] 2020-05-24 02:45
Thanks! I’ll check that too.

**Comment by jkeech** [comment] 2020-05-26 03:13
Closing as a duplicate of #518

**Closed by jkeech** 2020-05-26 03:13 UTC
