### ISSUE TITLE
Websockets are not supported by browser-based editor port forwarding

### ISSUE THREAD

**Issue by Chuxel** [MicrosoftDocs/vsonline#6] opened 2019-10-24 22:47 UTC
Currently the forwarding mechanism in VS Online's browser-based editor only supports http and https requests. Web sockets will not work even if served up in forwarded web content or used in JavaScript code. This can affect both user applications and extensions that use websockets from webviews.

However, the VS Online extensions for VS Code itself does not have this limitation.

**Comment by jkeech** [comment] 2019-11-03 20:48
Thanks for reporting this issue! Closing this as a duplicate of the broader issue #19.

**Closed by jkeech** 2019-11-03 20:48 UTC
Labels: enhancement

**Comment by Chuxel** [comment] 2019-11-03 22:09
Will update VS Code extension docs as well since there's a number of extensions affected.
