### ISSUE TITLE
Authentication failure on Firefox

### ISSUE THREAD

**Issue by rebornix** [MicrosoftDocs/vsonline#47] opened 2019-11-04 19:58 UTC
Kept seeing `Error: Authentication Failed` after logging to my account and redirected back to VSO.

**Comment by Priya91** [comment] 2019-11-04 21:22
Thanks for reporting, this is a known issue. Dupe of #34

**Comment by lostintangent** [comment] 2019-11-05 14:02
Closing this as a dupe of #34.

**Closed by lostintangent** 2019-11-05 14:02 UTC
