### ISSUE TITLE
Unable to clone git repo when creating environment

### ISSUE THREAD

**Issue by duydle499** [MicrosoftDocs/vsonline#353] opened 2020-03-18 15:10 UTC
I have a DevOps repo but I get an error when creating an environment:

"We are unable to clone this repository automatically"

**Comment by jkeech** [comment] 2020-03-18 15:13
Closing as a duplicate of #48. Creation of environments from Azure DevOps repos from the portal should be supported soon. It should also work today if you create from the VS Code extension.

**Closed by jkeech** 2020-03-18 15:13 UTC
