### ISSUE TITLE
Codespaces fails with private ACR image

### ISSUE THREAD

**Issue by rickardp** [MicrosoftDocs/vsonline#636] opened 2020-07-01 22:00 UTC
There is no obvious way to provide ACR credentials to be able to base the devcontainer image off a private image stored in an Azure Container Registry.

The container creation fails with:
Could not pull the image referenced in the Dockerfile

What is intended behavior here. I do not plan on putting my internal build system on a public container registry, how can I provide the credentials to the ACR somewhere? The ACR would accept the credentials I use to authenticate with Codespaces so if the JWT token was propagated to docker my use case would work.

**Comment by jkeech** [comment] 2020-07-01 22:17
Private registries are not supported yet, but it's something we plan to start working on soon. I'm going to close this as a duplicate of #360 so we can track there. Thanks!

**Closed** 2020-07-01 22:17 UTC

**Comment by rickardp** [comment] 2020-07-03 08:00
Good to hear it's coming. May I also suggest this is clearly documented? Because it was at least not clear to me that this was not expected to work.

**Comment by jkeech** [comment] 2020-07-06 20:50
@rickardp, yes, I agree, the docs could be clearer here. Thanks for the feedback! @nikmd23 @gregvanl FYI.
