### ISSUE TITLE
Support for HMR/Fast Refresh w/ Next.js

### ISSUE THREAD

**Issue by dmitryyankowski** [MicrosoftDocs/vsonline#579] opened 2020-06-11 08:55 UTC
Has anyone gotten HMR/Fast Refresh working on Codespaces w/ Next.js? The commands `yarn dev` and `yarn build && yarn start` work just fine (forwards port 3000).. however HMR/Fast Refresh doesn't seem to work. The page tries to go to `https://<workspace_url>-3000.app.online.visualstudio.com/_next/webpack-hmr?page=/` but it can't load it for some reason (it just eventually times out). This URL seem's to only accept the `text/event-stream` Content-Type.

Anyone have any ideas? :)

**Comment by plisy** [comment] 2020-06-11 23:22
Hello, right now, we don't support websockets in port forwarding in browser. We are working on adding the support.

I'm going to close this issue as a duplicate of #196.

Thank you for taking the time to report the issue.

**Closed by plisy** 2020-06-11 23:22 UTC
Labels: area: port forwarding
