### ISSUE TITLE
Something is intercepting the request body.

### ISSUE THREAD

**Issue by halfnibble** [MicrosoftDocs/vsonline#570] opened 2020-06-08 09:18 UTC
I have a simple webpack dev server setup, and an express api endpoint.

When I run my server from vs code online in the browser, and navigate to the custom domain provided by vs code online (for port 8080), something appears to intercept the xhr request body. it always gives me an empty body. `{ }`.

However, if I LiveShare the code without modification to vs code desktop, and run the server from there and go to the localhost:8080 page, my xhr request contains a body with all the data.

I can provide a minimal repro if that would help.

**Comment by chkn** [comment] 2020-06-08 16:39
Thanks for reporting this! Sending a request body currently doesn't work in port forwarding on web. We are tracking the issue already at #213.

We're in the process of developing a more complete port forwarding solution for web. In the meantime, you can use desktop VS Code, as you mentioned. Note that you can also connect desktop VS Code directly to a Codespace without having to LiveShare the code first.

Closing this issue as a duplicate of #213

**Closed by chkn** 2020-06-08 16:39 UTC
