### ISSUE TITLE
Configuration for Node 10.x not being respected

### ISSUE THREAD

**Issue by rgarita** [MicrosoftDocs/vsonline#182] opened 2019-11-13 23:41 UTC
I have created a project with customizations to tell VSO to build a Node 10 Container, but after the Environment creation, I'm still getting Node 12.x.

I'm trying to use this for SharePoint and SPFx, which is not compatible with 12.x yet. So I'm blocked. 

Check my repo https://github.com/rgarita/spfx-remote-container/.

The same config using Local Docker Containers works jut fine.

**Comment by jkeech** [comment] 2019-11-13 23:45
What customizations did you include to tell VSO to build a Node 10 container? Today, all environments have the same base image. Multiple versions of Node are installed, but only the LTS version is on the PATH by default. You should be able to modify the PATH though, or directly invoke the right version of node using a fully-qualified PATH.

#107 is tracking the ability to have the PATH automatically modified based on the node engine version that is declared.

**Comment by rgarita** [comment] 2019-11-13 23:50
Thanks @jkeech  for the quick respose.. 

I added a devcontainer.json file with:

````
{
    "name": "SPFx Container",
    "dockerFile": "Dockerfile",

    // Specifies a list of ports that should be published.
    "appPort": [4321],

    // Comment out the next line to run as root instead. Linux users, update
    // Dockerfile with your user's UID/GID if not 1000.
    "runArgs": [ "-u", "node" ],

    // Use 'settings' to set *default* container specific settings.json values on container create. 
    // You can edit these settings after create using File > Preferences > Settings > Remote.
    "settings": {
        "terminal.integrated.shell.linux": "/bin/bash"
    },

    // Specifies a command that should be run after the container has been created.
    "postCreateCommand": "npm install",

    "extensions": [
        "dbaeumer.vscode-eslint"
    ]
}
``
And a DockerFile with
````
  
#-------------------------------------------------------------------------------------------------------------
# Copyright (c) Building Information Systems LLC. All rights reserved.
# Licensed under the MIT License. See https://go.microsoft.com/fwlink/?linkid=2090316 for license information.
#-------------------------------------------------------------------------------------------------------------

FROM node:10

# Avoid warnings by switching to noninteractive
ENV DEBIAN_FRONTEND=noninteractive

# The node image comes with a base non-root 'node' user which this Dockerfile
# gives sudo access. However, for Linux, this user's GID/UID must match your local
# user UID/GID to avoid permission issues with bind mounts. Update USER_UID / USER_GID 
# if yours is not 1000. See https://aka.ms/vscode-remote/containers/non-root-user.
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Configure apt and install packages
RUN apt-get update \
    && apt-get -y install --no-install-recommends apt-utils dialog 2>&1 \ 
    #
    # Verify git and needed tools are installed
    && apt-get install -y git procps \
    #
    # Remove outdated yarn from /opt and install via package 
    # so it can be easily updated via apt-get upgrade yarn
    && rm -rf /opt/yarn-* \
    && rm -f /usr/local/bin/yarn \
    && rm -f /usr/local/bin/yarnpkg \
    && apt-get install -y curl apt-transport-https lsb-release \
    && curl -sS https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/pubkey.gpg | apt-key add - 2>/dev/null \
    && echo "deb https://dl.yarnpkg.com/$(lsb_release -is | tr '[:upper:]' '[:lower:]')/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update \
    && apt-get -y install --no-install-recommends yarn \
    #
    # Install eslint globally
    && npm install -g eslint \
    #
    # Install SPFx Deps
    && npm install -g yo gulp \
    && npm install -g @microsoft/generator-sharepoint \
    #
    # Create a non-root user to use if preferred - see https://aka.ms/vscode-remote/containers/non-root-user.
    && if [ "$USER_GID" != "1000" ]; then groupmod node --gid $USER_GID; fi \
    && if [ "$USER_UID" != "1000" ]; then usermod --uid $USER_UID node; fi \
    # [Optional] Add sudo support for non-root users
    && apt-get install -y sudo \
    && echo node ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/node \
    && chmod 0440 /etc/sudoers.d/node \
    #
    # Clean up
    && apt-get autoremove -y \
    && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/*

# Switch back to dialog for any ad-hoc use of apt-get
ENV DEBIAN_FRONTEND=
``

**Comment by rgarita** [comment] 2019-11-14 00:10
@jkeech  The usage of a DockerFile is a valid customization approach? I thought it is.

**Comment by jkeech** [comment] 2019-11-14 00:17
@rgarita, customer Dockerfiles are not supported yet. We are working on adding that though, and should make it available via an opt-in setting/feature flag in a week or two. #15 is tracking the work to support custom Dockerfiles and custom pre-built images.

**Comment by jkeech** [comment] 2019-11-15 21:35
Closing this as a duplicate of #15

**Closed by jkeech** 2019-11-15 21:35 UTC
