### ISSUE TITLE
Cannot clone Azure repo in new environment

### ISSUE THREAD

**Issue by haodeon** [MicrosoftDocs/vsonline#352] opened 2020-03-18 07:37 UTC
I am unable to create any new environments and my existing environments (which I have deleted) are unable to push to my repos.

I am using Azure Repos, creating the environment using the vs code extension.

This issue only just started happening for me in the last 12 hours, last night I was able to push fine.

The error I am getting is my sign in token has expired. I have tried to delete from my computer all credentials related to VS Code or Azure and I am not able to resolve this issue.

I am not getting the pop up window to prompt for credentials during the clone process (or the push process for that matter).

I can clone locally just fine and push changes back locally.

I have also tried from two computers and they are both exhibiting the same problem.

```
Configuration starting...
COMMAND: git ls-remote https://xxxxx@dev.azure.com/xxxxxx/xxxxxx/_git/xxxxx heads/master
warning: invalid credential line: [CLI E] Microsoft.Cascade.Rpc.RemoteException: Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug.
fatal: could not read Password for 'https://xxxxxxxx@dev.azure.com': terminal prompts disabled
git process exited with exit code 128
COMMAND: git clone --depth 1 https://xxxxxxxx@dev.azure.com/xxxxx/xxxxx/_git/xxxx "/root/workspace"
Cloning into '/root/workspace'...
warning: invalid credential line: [CLI E] Microsoft.Cascade.Rpc.RemoteException: Your sign in token has expired. Please sign out and in again to refresh it. If the issue persists, please log a bug.
fatal: could not read Password for 'https://xxxxxxx@dev.azure.com': terminal prompts disabled
git process exited with exit code 128
Terminal exited. Press any key to close it
```

**Comment by haodeon** [comment] 2020-03-18 08:26
I created a new plan in westus2 and I managed to create a new environment and clone my repo.

My other plan is SE Asia.

**Comment by jkeech** [comment] 2020-04-01 15:30
@haodeon, the plan should not affect the git credentials during creation. Since it's working in westus2 for you, can you retry in the other plan from the same machine?

Also, is it possible that you were connected from two different machines simultaneously? If so, there's a bug where the credentials will be queried from the first machine that joined, rather than the one you are actively using.

As an example, say you have the web client `A` and VS Code client `B`. They could be on the same machine or different machines. If you first connected to the environment from `A`, but did not have the Azure DevOps oauth token stored in the browser, git pull/push would fail from that machine. Then if you connected from `B` while `A` was still connected, if you can git pull/push from `B`, it would actually query credentials from the `A` client, which still won't work, even if `B` does have the git credentials stored locally.

**Comment by haodeon** [comment] 2020-04-01 20:32
Hi,

I cannot reproduce the error anymore. After a few days of using westus2 I decided to try SE Asia again and it worked. This was about 2 or 3 days ago.

One thing I noticed before it stopped working for me completely was it kept asking me to login for every single git operation (fetch and push ended up being two logins for instance).

I put up with this for a couple of days and then on the day I reported the issue it failed completely.

Regarding multiple machines. I do have two machines I connect from. However, I do not connect from both at the same time. Usually there is at least 30 minutes between changing computers (my suspend period is 30 minutes).

I know this sounds weird but it felt to me like the k8s cluster VSO runs on was somehow caching an expired token. On the day I created a new environment on westus2, I did try and go back to SE Asia to test. It continued to be broken for me and nothing had changed on my local machine.
If westus2 worked fine with my oauth token then SE Asia should work too but it did not.

**Comment by jkeech** [comment] 2020-04-01 21:09
@haodeon, interesting. We do not store credentials on our service or in the cluster when the services are running -- git credentials stay on the clients and are queried directly from the remote environment when they are needed (such as running `git pull`). We do roll out new service code to regions at different times though. It's possible we had an inadvertent breaking change in a service rollout that a client update later fixed.

I'm going to go ahead and close this issue for now since things are working for you and we can't reproduce the issue, but please submit a new issue if this happens again. Thanks!

**Closed by jkeech** 2020-04-01 21:09 UTC
