### ISSUE TITLE
vso start on linux fails with permission issues

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/vsonline#400] opened 2020-04-10 18:25 UTC
when executing `vso start --service` on linux i get the following error. it looks like the service is not running as the actual logged in user?

```
[2020-04-10 18:22:38.687 CLI I] vso v1.0.1961.39102 (pid: 97091)
[CLI E] Process terminating: True
 System.UnauthorizedAccessException: Access to the path '/home/myuser/.vs-liveshare-settings.json' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileO
ptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.CloudEnvironments.CLI.CliSettings.SaveSettingsToFile(String filename) in E:\A\_work\122\s\src\VSOnline\C
LI\CliSettings.cs:line 75
   at Microsoft.CloudEnvironments.CLI.CliSettings..ctor(TraceSource trace, FilePathProviderBase filePathProvider, CloudE
nvironmentInputProviderBase inputProvider, String filename) in E:\A\_work\122\s\src\VSOnline\CLI\CliSettings.cs:line 27
   at Microsoft.CloudEnvironments.CLI.Program.RegisterCommands(TraceSource trace, TraceSource allTrace, IConfigurationRo
ot config) in E:\A\_work\122\s\src\VSOnline\CLI\Program.cs:line 192
   at Microsoft.CloudEnvironments.CLI.Program.Main(String[] args) in E:\A\_work\122\s\src\VSOnline\CLI\Program.cs:line 1
11
```

and the process is stuck at 
`[2020-04-10 18:22:25.230 CLI I] Waiting for environment to become available...`

**Comment by taiyosogawa** [comment] 2020-04-10 19:14
Thanks for trying out on Linux, too. To understand what's going on:
1) Did you run `vso start` as the user `myuser` (or whatever was shown originally if you replaced with `myuser`)?
2) Could you `ls -l /home/myuser/.vs-liveshare-settings.json` to see if it owned by anyone other than `myuser`?
3) Could you `ps aux | grep vsls-agent` and `ps aux | grep vso` to see if any of those processes are running as anyone other than `myuser`?

**Comment by OneCyrus** [comment] 2020-04-10 19:28
ok i see the issue

1. i run with myuser but did a `sudo vso start --service`

2. 
```
myuser@sys374:~$ ls -l /home/myuser/.vs-liveshare-settings.json
-rw-r--r-- 1 root root 429 Apr 10 18:34 /home/myuser/.vs-liveshare-settings.json
```

3.
```
myuser@sys374:~$ ps aux | grep vsls-agent
myuser    99102  0.0  0.0  13136  1052 pts/2    S+   19:19   0:00 grep --color=auto vsls-agent
myuser@sys374:~$ ps aux | grep vso
root      97471  0.0  0.0  68640  4392 pts/1    S+   18:34   0:00 sudo vso start --service
root      97472  0.3  0.9 3825804 100020 pts/1  Sl+  18:34   0:10 vso start --service
```

so it looks l,ike the sudo mixes the accounts up. but when running vso start without sudo i get the following:

```
[2020-04-10 19:25:08.652 CLI I] Creating your environment...
[2020-04-10 19:25:09.955 CLI I] Saving local configurations...
[2020-04-10 19:25:10.096 CLI I] Authenticating...
[2020-04-10 19:25:10.116 CLI E] [!ERROR] Permission denied /tmp/CoreFxPipe_VSLS-SH
```

**Comment by taiyosogawa** [comment] 2020-04-10 20:02
Ah, I see. Our cleanup logic is unfortunately limited right now, but we'll work on improving that because this will definitely be encountered again. 

Try `sudo vso stop`, but if that fails, this should get you in a clean state:

kill all vsls-agent and vso processes
```
sudo rm -r ~/.vsonline
sudo rm /tmp/CoreFxPipe_VSLS-SH
sudo rm /home/myuser/.vs-liveshare-settings.json
sudo rm /home/myuser/.vs-liveshare-keychain
```

Our docs have more details why we discourage running as sudo (because the user you run as will determine the user you connect as). We can definitely add logic to detect someone running as root point out the appropriate information. We don't expect anyone to read through all the docs before getting started 😵

**Comment by jkeech** [comment] 2020-04-10 20:04
@taiyosogawa is the log output path configurable? It sounds like the issue is that a non-root user doesn't always have permissions to write logs to `/tmp`.

**Comment by taiyosogawa** [comment] 2020-04-10 20:06
Good question - not that I'm aware of.

@OneCyrus, You may need to `rm -r /tmp/VSFeedbackVSRTCLogs`, too.

**Comment by OneCyrus** [comment] 2020-04-11 10:13
after cleaning it up it works now. thanks! 

a warning about sudo in the actual cli would be nice. also a full cleanup with vso stop would help too.

**Comment by taiyosogawa** [comment] 2020-04-15 18:11
Glad to hear it worked! I'll close this when we roll out the improvements I mentioned.

**Comment by JtMotoX** [comment] 2020-04-15 18:37
### macOS 10.15.3

I am also getting permission denied but my output is slightly different than the OP.  I have tried running with and without persistent daemon but getting permission denied.

#### Pre-steps:
```
$ wget https://vsoagentdownloads.blob.core.windows.net/vsoagent/VSOAgent_osx_3633968.zip
. . .
$ unzip VSOAgent_osx_3633968.zip
. . .
$ chmod 755 ./vso
$ ./vso -v   
[2020-04-15 18:19:17.505 CLI I] vso v1.0.2005.59801 (pid: 19069)
Command-line interface for Visual Studio Online
1.0.2005
$ sudo ./vso stop                                                                        
[2020-04-15 18:31:08.190 CLI I] vso v1.0.2005.59801 (pid: 19327)
[2020-04-15 18:31:08.639 CLI E] Could not find information about your environment to remove.
$ sudo rm -rf ~/.vsonline ~/.vs-liveshare* /tmp/CoreFxPipe_VSLS* /tmp/VSFeedbackVSRTCLogs
```

#### Start VSO:
```
$ ./vso start
[2020-04-15 18:32:41.256 CLI I] vso v1.0.2005.59801 (pid: 19346)
[2020-04-15 18:32:41.655 CLI I] Authenticating...
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code *** to authenticate.
Would you like to run as a persistent service/daemon? [Y/n]: n
[2020-04-15 18:33:08.698 CLI I] Will run as a process
[2020-04-15 18:33:09.187 CLI I] A VSO plan is required to register your environment.
[2020-04-15 18:33:09.189 CLI I] Using VSO plan: /subscriptions/***/resourceGroups/***/providers/Microsoft.VSOnline/plans/***
Enter an environment name or blank to use [***]: 
[2020-04-15 18:33:11.871 CLI I] Creating your environment...
[2020-04-15 18:33:16.732 CLI I] Saving local configurations...
[2020-04-15 18:33:17.190 CLI I] Authenticating...
[2020-04-15 18:33:17.325 CLI E] [!ERROR] Permission denied
```

**Comment by taiyosogawa** [comment] 2020-04-22 21:06
@JtMotoX, sorry for the late reply. I'm wondering if there was a vsls-agent process running as that wasn't killed. I realize it is likely too late to check now.

We'll be publishing a set of improvements to `vso stop` next week which should do a better job of getting back into a clean state (or displaying what cannot be done automatically). I'll post when those are available.

**Comment by JtMotoX** [comment] 2020-04-23 02:52
@taiyosogawa, yeah it is very possible that the vsls-agent was running.  As mentioned in my last comment, any idea on the "Permission denied" I am getting when trying to vso start?

**Comment by taiyosogawa** [comment] 2020-05-05 20:59
Hi, I think the "Permission denied" is from trying to access an RPC pipe was created/protected by another user. We've deployed some changes to ensure each user gets their own pipe. When you get a chance, try it out.

I'll close out this issue since we've made updates to address the original problem. Please feel free to open another issue if you're still seeing problems, and thanks for engaging with us @OneCyrus and @JtMotoX.

**Closed by taiyosogawa** 2020-05-05 20:59 UTC
Labels: area: self-hosting, bug
