### ISSUE TITLE
[Clarification] Does port forwarding should support UDP? (If not, can it?)

### ISSUE THREAD

**Issue by nathansoz** [MicrosoftDocs/vsonline#212] opened 2019-11-22 23:23 UTC
I haven't had a chance to test it, but I saw another issue that makes me think that UDP port forwarding isn't supported. There are some dev use cases that this would unlock for my team and I'm wondering if it could be supported if it isn't.

**Comment by lostintangent** [comment] 2019-11-22 23:55
We don’t currently support UDP (#19 is tracking that), but we’re working on adding support for it right now. Out of curiosity: what are the dev use cases you have in mind? It would be super helpful to have specific scenarios in mind, as we test/build out support for UDP/TCP.

**Comment by lostintangent** [comment] 2019-11-23 01:23
I’m going to close this as a duplicate of #19, but please re-open it if you don’t think #19 accurately reflects your request. Thanks!

**Closed by lostintangent** 2019-11-23 01:23 UTC

**Comment by nathansoz** [comment] 2019-11-26 23:41
@lostintangent sorry for getting back to this late. I'll post on 19 to ensure that my use case (in this case, a game server, is covered)
