### ISSUE TITLE
when i reconnect it takes forever and doesn't work

### ISSUE THREAD

**Issue by simkimsia** [MicrosoftDocs/vsonline#455] opened 2020-05-05 07:17 UTC
i am using vs codespaces extension in vscode. and i successfully finished the tutorial.

this is what it looks like after my successful completion of tutorial

![image-20200503143848521](https://user-images.githubusercontent.com/245021/81042813-8b0fa480-8ee3-11ea-9fa9-9766749e2b44.png)

Then i turn off and return on now it takes forever to reconnect and doesn't work

this is what it looks like

![image](https://user-images.githubusercontent.com/245021/81042784-77643e00-8ee3-11ea-8370-da360bf8e3ed.png)

**Comment by abuchholtzau** [comment] 2020-05-07 17:49
When you say you "turn off", do you mean you disconnect and suspend the Codespace?
Can you check the Output for VS Codespaces for any errors?

**Comment by simkimsia** [comment] 2020-05-12 05:42
> do you mean you disconnect and suspend the Codespace?
Yes

> Can you check the Output for VS Codespaces for any errors?
How?

**Comment by simkimsia** [comment] 2020-05-12 05:42
![image](https://user-images.githubusercontent.com/245021/81642635-6ae96380-9456-11ea-8a4e-f394a9003290.png)This is a screencap I had with the paid support at Azure. Who's PG?

**Comment by jkeech** [comment] 2020-05-15 04:23
Hi @simkimsia, I believe PG stands for "product group", which means the Codespaces dev team. Have you heard back from support yet with answers to your questions?

For your original post, if you go to https://online.visualstudio.com/environments and click on your environment, does it connect? If not, can you share the environment id or paste the url that it opens when you try to connect?

**Comment by simkimsia** [comment] 2020-05-23 06:09
Hi @jkeech 

I have tried.

It works on https://online.visualstudio.com/environments  but not in vscode desktop app which takes forever and doesn't work.

What should I do?

By the way, I appreciate that this is still under preview so I'm sure a lot of amazing improvements are happening.

But please don't forward me to another team handling VSCode desktop

I have paid for support on Azure. Does it cover vscode online? I think it should since I can see the charges I have spent on vscode online on my Azure portal.

I already came here via the Azure paid support personnel. And I just want one consistent place for me to get all my queries on vscode online answered.

I am okay with delays in answers. 

Thank you.

**Comment by jkeech** [comment] 2020-05-26 03:39
Hey @simkimsia, this is the right place for support for Codespaces, which includes both the desktop extension and the web-based editor. Glad to hear that it's working in the web. We'll work with you to figure out what's going on on the desktop.

We will likely need to look at the logs on the client side to see what it going on with it not connecting. Can you provide the following information to help us troubleshoot?
 1) Which OS and VS Code version are you on?
 2) What steps are you taking to start the connection?
 3) Do you see the Codespace listed in the remote explorer viewlet? 
 4) Can you confirm the Codespace is in an "Available" state in the web portal before connecting in VS Code?
 5) Can you share the contents of the `Codespaces` output channel in VS Code, both before you connect and after it loads the new window to connect?

**Comment by simkimsia** [comment] 2020-05-26 06:08
>Which OS and VS Code version are you on ?

![image](https://user-images.githubusercontent.com/245021/82865758-1bc52780-9f5a-11ea-804f-07c20f09b23e.png)
![image](https://user-images.githubusercontent.com/245021/82865776-2384cc00-9f5a-11ea-9692-29ad9ab70dd9.png)

Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

> hat steps are you taking to start the connection?
![image](https://user-images.githubusercontent.com/245021/82865808-37c8c900-9f5a-11ea-8cf4-e74463351d02.png)
Then I choose connect

> Do you see the Codespace listed in the remote explorer viewlet?
what do you mean by remote explorer viewlet?

> Can you confirm the Codespace is in an "Available" state in the web portal before connecting in VS Code?

Yes

> Can you share the contents of the Codespaces output channel in VS Code, both before you connect and after it loads the new window to connect?

Can you be more specific abt output channel?

**Comment by jkeech** [comment] 2020-05-26 22:50
> what do you mean by remote explorer viewlet?

@simkimsia, There is some UI in VS Code to manage the Codespaces as well as the command palette commands. I expect that the Codespaces also show up in this UI, but just want to double check. See this screenshot for more details:

![image](https://user-images.githubusercontent.com/746020/82957517-ff2fec00-9f67-11ea-86b4-f98726651091.png)


> Can you be more specific abt output channel?

You can turn on the Output view and then switch to the "VS Codespaces" log in the drop down:
![image](https://user-images.githubusercontent.com/746020/82957727-939a4e80-9f68-11ea-8bb3-9f8010a5585c.png)

**Comment by simkimsia** [comment] 2020-05-28 06:38
Hi there, I have a 5 min video that explains what I did, but how do I send you securely?

**Comment by jkeech** [comment] 2020-05-28 16:15
@simkimsia, feel free to email it to me: john.keech (at) microsoft (dot) com. You can attach the video directly or upload to a private youtube video and share the link. Also, if you could attach the log file contents directly would be helpful. Thanks!

**Comment by simkimsia** [comment] 2020-05-29 06:41
@jkeech done

and i included the log from the output

Thank you. 

The next time i will reply will be in 5 days time on 2020-06-03 Wednesday Thank you

**Comment by jkeech** [comment] 2020-06-03 00:18
@simkimsia, thanks! I filed the VS Code issue referenced above to get some help investigating the VS Code behavior where the remote resolver is not fully kicking in.

Is there any public repo that this also reproduces on for you? It would be helpful to have some repro steps we that we can use to replicate the problem. This isn't an issue that I've ever seen before or been able to reproduce so far.

**Comment by simkimsia** [comment] 2020-06-03 03:24
It’s a private repo

I will try on public repo but it will take at least 10 days from now

If u don’t mind waiting

**Comment by jkeech** [comment] 2020-06-03 03:30
@simkimsia, there’s no problem waiting. Please let us know whenever you have an update. In the meantime we will continue to try to figure out what is going on with the information we already have. Thanks!

**Comment by jkeech** [comment] 2020-06-08 21:56
It looks like this is the same issue as #499. Let's track over on that issue. Closing this one.

**Closed by jkeech** 2020-06-08 21:56 UTC
