### ISSUE TITLE
cannot edit code with VSCode Online when using "Layout United States International Keyboard"

### ISSUE THREAD

**Issue by lukka** [MicrosoftDocs/vsonline#138] opened 2019-11-08 23:54 UTC
With keyboard layout "Layout United States International Keyboard", the dead keys do not show up, all you get is a blank space instead. Note the missing double quotes in the animation.

![no_dead_keys](https://user-images.githubusercontent.com/681992/68518250-fd0e7600-023f-11ea-9b5a-03202669f61c.gif)

**Comment by egamma** [comment] 2019-11-09 15:45
Duplicate of https://github.com/microsoft/vscode/issues/83993

**Closed** 2019-11-10 02:39 UTC
