### ISSUE TITLE
vsls-agent cpu usage never dies down

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#23] opened 2019-11-01 02:47 UTC
**Repo**
1. Set up a new environment for `Microsoft/TypeScript`
1. Connect and wait for setup to complete
1. Wait for a little while to give it time to settle down 
1. Now in the environment, run `top` in the terminal

**Bug**
Cpu usage is always between 100 and 200%. Here's the process:

```
vsonline     51  139  1.8 4460216 302400 ?      SLl  01:13  12:25 /.vsonline/bin/vsls-agent --pipe VSLS --service https://prod.liveshare.vsengsaas.visualstudio.com/ --autoexit --
``` 

/cc @kieferrm

**Comment by jasongin** [comment] 2019-12-05 21:14
I can reproduce this. I suspect it happens for any repo containing a very large number of files. We'll investigate.

**Comment by jasongin** [comment] 2019-12-05 22:42
It looks like the problem is related to the file-watcher in `vsls-agent`. Cloning a large repo after the environment was initialized causes many thousands of file-watcher events to get processed. But actually those events aren't used for anything in this case, so we should probably disable the file-watcher.

The CPU usage should eventually stop after several minutes. Alternatively, suspending and resuming the environment (after the `git clone` has completed) eliminates the high CPU usage immediately.

**Comment by jasongin** [comment] 2019-12-09 23:09
A fix for this issue is checked in and will be deployed soon.

**Comment by jasongin** [comment] 2019-12-19 21:30
I confirmed the fix. CPU usage drops to near zero after the initial git clone and build are finished.

**Closed by jasongin** 2019-12-19 21:30 UTC
Labels: area: performance, bug
