### ISSUE TITLE
cannot open authentication link in browser

### ISSUE THREAD

**Issue by githubfzq** [MicrosoftDocs/vsonline#266] opened 2019-12-22 16:15 UTC
I have opened [this issue](https://github.com/microsoft/vscode/issues/86830#issue-537091743) in vscode. 
> * VSCode Version: 1.40.0
> * OS Version: Ubuntu 18.04
> 
> Steps to Reproduce:
> 
> 1. In command, I typed ">vs online: sign in", and enter.
>    ![image](https://user-images.githubusercontent.com/19188149/70730433-e62bd980-1d3f-11ea-8812-9b37bd472598.png)
> 2. A notification indicated.
>    ![image](https://user-images.githubusercontent.com/19188149/70730601-415dcc00-1d40-11ea-8952-2cf96999189b.png)
> 3. After a while, vs code seems to try to open link in browser.
>    ![image](https://user-images.githubusercontent.com/19188149/70730775-8eda3900-1d40-11ea-9375-bf532b7f744a.png)
> 4. But the page in browser is HTML code opened from local file, NOT a web page.
>    ![image](https://user-images.githubusercontent.com/19188149/70730932-d4970180-1d40-11ea-9771-eb52271df4d5.png)
> 
> This issue occurs not only when signing into vscode online, but also whenever vscode try to open an external link. A cached page file with HTML source file is always opened.
> 
> Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jkeech** [comment] 2019-12-26 18:16
Hi @githubfzq, sorry are having issues opening links from VS Code. I've replied to the original issue you filed on the vscode repo. I think you were correct that this is a VS Code issue, and it is not specific to the VS Online extension. I've asked the VS Code team to take a closer look at your issue. I'll leave this open here for tracking until the issue is re-opened on the vscode repo. Thanks!

**Comment by lostintangent** [comment] 2020-03-21 16:08
@jkeech It seems like the VS Code team closed that bug and think it’s a VSO issue?

**Comment by jkeech** [comment] 2020-03-26 00:21
@lostintangent, no, they didn't investigate after I commented. I don't see how this could be a VSO issue. This is a client-side VS Code issue opening any link from the VS Code install. I think the VS Code issue needs to be reopened.

**Comment by jkeech** [comment] 2020-03-26 00:22
I'm going to go ahead and close this issue since it's not a VSO issue.

**Closed by jkeech** 2020-03-26 00:22 UTC
Labels: area: authentication, bug
