### ISSUE TITLE
Run containers in the host network by default

### ISSUE THREAD

**Issue by fabiom-zz** [MicrosoftDocs/vsonline#357] opened 2020-03-22 21:02 UTC
I'm having an issue with the networking support for Docker in an VS Online environment. I can create containers, but **Docker** port fowarding is not working. **NOTE:** I'm not talking about VS Online port forwarding, that works great for me.

In other words, once Docker port fowarding works, I assume VS Online port forwarding will be just fine.

Steps to reproduce:

* Create VS Online environment
* In Terminal, create an nginx Docker container that forwards the local port 9090 to the container port 80:

`sudo docker run --name my-nginx -p 9090:80  -d nginx`

* When I ran 

`wget 127.0.0.1:9090`

I get `Connecting to 127.0.0.1:9090... failed: Connection refused.`

* I inspected the container and got the container IP (show in `"IPAddress"`) from the command below:

`sudo docker container inspect my-nginx`

* I can successfully connect to nginx via that IP

`wget 172.17.03:80`

My conclusion is that the container is running properly but Docker is unable to forward the local port 9090 to port 80 in the VS Online environment.

I saw articles saying that Docker relies on `iptables` for port fowarding but the VS Online environment doesn't seem to have it. Could that be the issue?

**Comment by nikmd23** [comment] 2020-03-25 12:15
Good question @fabiom-zz! Looping in @jkeech and @edgonmsft

**Comment by jkeech** [comment] 2020-03-25 15:43
This is related to #314. The main environment container is not currently run in host networking mode, but it's something we are changing very soon.

**Comment by lostintangent** [comment] 2020-04-04 18:48
@jkeech @edgonmsft Could this be closed as a duplicate of #314, or is there unique product work we’d need to do to suport this?

**Comment by jkeech** [comment] 2020-04-04 19:36
This change will be deployed next week. It won't change behavior for existing environments, but any newly created environment will have host networking enabled when you use the default image.

**Comment by edgonmsft** [comment] 2020-04-22 16:24
This is deployed now.

**Closed by edgonmsft** 2020-04-22 16:24 UTC
Labels: area: docker, bug
