### ISSUE TITLE
Live Share extension sets DOTNET_ROOT environment variable on extension host process which breaks `dotnet run` for apps

### ISSUE THREAD

**Issue by bartr** [MicrosoftDocs/vsonline#482] opened 2020-05-09 20:22 UTC
csproj file
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
...

dotnet run shows the following error:

It was not possible to find any compatible framework version
The framework Microsoft.AspNetCore.App version 3.1.0 was not found
  - no frameworks were found

dotnet --version returns 3.1.100
dotnet restore works
dotnet build works
dotnet clean works

Suspending and restarting the codespace usually works

Reloading the C# extension usually works

Eventually, some combination of those works

**Comment by jkeech** [comment] 2020-05-10 03:33
@bartr, can you provide a sample repo and the exact steps you take to reproduce this problem? It sounds like it does not happen consistently. Is that correct?

**Comment by bartr** [comment] 2020-05-10 04:54
It’s pretty consistent for me. Not 100%, but seems around 90%

Repro

- Start here: https://online.visualstudio.com/environments
  - Create Codespace
    - Unique name
    - Repo: https://github.com/bartr/testrepo
      - this is just dotnet new webapi with readme and gitignore
    - dotfiles blank

- Wait for container to start
- Go to terminal

```
cd src
dotnet run

```

Error

```
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '3.1.0' was not found.
  - No frameworks were found.
```

- Hit the back button to go back to environments
- Connect to the codespace

```
cd src
dotnet run
```

Works

**Comment by bartr** [comment] 2020-05-10 05:12
I think I found the problem.  If I run ```unset DOTNET_ROOT``` before ```dotnet run``` it works without reconnecting.

This is what my DOTNET_ROOT is set to at first run

```
DOTNET_ROOT=/home/vsonline/.vscode-remote/data/User/globalStorage/ms-vsliveshare.vsliveshare/dotnet-3.1.1
```

**Comment by jkeech** [comment] 2020-05-10 05:39
@BrunoGuardia, do you know why Live Share is setting DOTNET_ROOT of n the VS Code extension host process during the first activation? It seems to break other dotnet apps in the same process tree.

**Comment by srivatsn** [comment] 2020-05-10 16:18
LiveShare should be setting DOTNET_ROOT only for the vsls-agent process it launches. Looks like a bug that it's setting it for the ext host process itself.

**Comment by jkeech** [comment] 2020-05-10 19:12
I've confirmed that Live Share is setting the variables on `process.env` in the extension host process when spinning up the agent. Live Share should instead be modifying the environment only for the child agent process, and not for the whole extension host process.

This only seems to affect remote scenarios (including Codespaces) since integrated terminals are spun up using the extension host process in remote sceanrios, which has the modified environment variables from the Live Share extension.

**Comment by BrunoGuardia** [comment] 2020-05-16 01:30
Fix is in master

**Comment by bartr** [comment] 2020-05-16 19:23
Verified this is working as expected on Codespaces.

**Comment by jkeech** [comment] 2020-05-16 20:01
@BrunoGuardia, has the fix been released yet? My understanding is that it’s not published yet, but this would only happen on the first time accessing a given Codespace since that is when Live Share is downloading the .NET Core runtime.

@bartr, I would expect this problem to still occur on new Codespaces until the fixed Live Share extension is published.

**Comment by bartr** [comment] 2020-05-16 20:13
I just checked again with bartr/testrepo (basically a dotnet new webapi) and made sure my dotfiles were blank.  `cd src && dotnet run` works for me and `env |grep DOTNET` doesn't include the DOTNET_ROOT like it did before.

**Comment by BrunoGuardia** [comment] 2020-05-17 17:20
As indicated above, the fix is in master. We don't plan to release next week due to //build, so the release would be ready the week after.

**Comment by BrunoGuardia** [comment] 2020-05-29 00:24
This is now fixed and released. Should be closed

**Closed** 2020-05-29 01:14 UTC
Labels: area: extensions, bug
