### ISSUE TITLE
Intermittent failure on load

### ISSUE THREAD

**Issue by larvacea** [MicrosoftDocs/vsonline#295] opened 2020-01-29 15:32 UTC
Issue Type: <b>Bug</b>

Intermittently on start or window-reload, VS Code fails to find the VS Online server, and simultaneously suggests that I install the Remote: WSL extension. I have installed that extension, but somehow whatever makes VS Online fail also convinces VS that it should recommend Remote: WSL.

Closing VS Code and relaunching it invariably (so far) fixes the problem, so it is just an annoyance. I am hoping that telemetry or logs might help you with this. Especially since telemetry is what I do :).

Extension version: 1.0.1507
VS Code version: Code - Insiders 1.42.0-insider (be9c72410acc677070685a616773b122f4c5e141, 2020-01-29T05:39:07.145Z)
OS version: Windows_NT x64 10.0.19555
Remote OS version: Linux x64 5.0.0-1028-azure

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|VS Online: kcb5|
|OS|Linux x64 5.0.0-1028-azure|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2294)|
|Memory (System)|15.64GB (12.39GB free)|
|VM|0%|
</details>

**Comment by jkeech** [comment] 2020-01-29 16:55
Thanks for reporting this issue. There is a fixed timeout in in the VS Code remote protocol (I believe 20 seconds) for the connection to be established. If it takes longer than that to download the matching VS Code server version and start it up, then the initial connection fails. When you refresh, the previous server process is still running, so it can connect much faster, which causes it to succeed before hitting the timeout.

We have seen some issues like this before, such as #215. This is another indication that we need to raise the initial connection timeout. I'm going to go ahead and close this issue as a duplicate of #215.

**Closed by jkeech** 2020-01-29 16:55 UTC
