### ISSUE TITLE
Can't type quotes

### ISSUE THREAD

**Issue by sadasant** [MicrosoftDocs/vsonline#68] opened 2019-11-05 15:07 UTC
I'm using VSCode online, the web version, and I'm unable to type single quotes, double quotes and symbols like `.

I am using US International as my keyboard layout locally. The online editor does let me write accented letters, like: áéíóú, etc.

So far I've been managing by copying and pasting these symbols. It hasn't stopped me from using the site, but it is kind of weird.

I'm using Chrome version 78.0.3904.70 (Official Build) (64-bit) on the latest available Window version.

**Comment by Chuxel** [comment] 2019-11-05 15:12
//cc: @rebornix @bpasero

**Comment by alexandrudima** [comment] 2019-11-05 15:14
Let's track at https://github.com/microsoft/vscode/issues/83993

**Comment by Chuxel** [comment] 2019-11-05 15:14
Closing as dupe of microsoft/vscode#83993

**Closed by Chuxel** 2019-11-05 15:14 UTC
