### ISSUE TITLE
Connect to Azure DevOps repos from the web

### ISSUE THREAD

**Issue by imsam67** [MicrosoftDocs/vsonline#55] opened 2019-11-04 23:38 UTC
Looks like, currently we can only use GitHub for source control. What about Azure DevOps repos? Will we be able to connect to them?

**Comment by jobullen** [comment] 2019-11-04 23:56
Put the entire URL to the GIT repo in Azures DevOps in the Git Repository field. It connects across. Looks like the default is GitHub if you only specify the name and repo combination.

**Comment by cmbrose** [comment] 2019-11-05 00:01
@jobullen is correct - in VS Code, you can create an environment from an Azure DevOps repo by giving the full URL (github.com is assumed if you only provide the short version)

For the web client, as mentioned in #48 we currently don't support creating from Azure DevOps repos in that client but that work is in progress.  In the meantime, you could create the environment from VS Code and then connect to it from the web portal.

**Comment by srivatsn** [comment] 2019-11-05 04:00
Closing as dupe of #48

**Closed by srivatsn** 2019-11-05 04:00 UTC
Labels: area:webapp, enhancement
