### ISSUE TITLE
How to connect Docker localhost?

### ISSUE THREAD

**Issue by amowu** [MicrosoftDocs/vsonline#374] opened 2020-04-02 08:33 UTC
In VS Code Online，I run this command in terminal to start a PostgresSQL server:

```bash
$ docker run -d -p 5432:5432 circleci/postgres:11-alpine
```

And I have already added PostgresSQL default port to the `forwardPorts`:

```json
{
  "forwardPorts": [5432],
}
```

But when I run my Rails application in VS Code Online, it could not connect PostgresSQL by `localhost:5432`.

**Comment by edgonmsft** [comment] 2020-04-02 16:49
Hi!

The issue right now is that the container is not created with host networking by default. This will be fixed soon. 

In the meantime one option is for you to create a custom container and add --network host to the run arguments.

I have this example repository:
https://github.com/edgonmsft/host-networking-example.git

After that I just ran docker run this way and I could connect to PostgreSQL:
docker run -d -p 5432:5432 -e POSTGRES_USER=root circleci/postgres:11-alpine

**Comment by jkeech** [comment] 2020-04-02 16:53
Related to #314

**Comment by lostintangent** [comment] 2020-04-04 19:05
Closing this as a duplicate of #357, which is tracking the work to run containers on the host network by default 👍

**Closed by lostintangent** 2020-04-04 19:05 UTC
