### ISSUE TITLE
Reload Environment when devcontainer.json changes.

### ISSUE THREAD

**Issue by paulgmiller** [MicrosoftDocs/vsonline#604] opened 2020-06-20 22:29 UTC
Seems like I always get the settigns from the .devcontainer* in my repo's master branch and I can't reload it after entering the code space. 
This makes it hard to test on the web ui (I think I could

Having a way to reload the environment after .devcontainer* changes would be good both for trying to set up existing repositories to work (where often it's hard to iterate in master) or going back to older release branches where the .devcontainer used an older image/dockerfile. 

Could also solve this by giving a branch name when creating the enviroment (couldn't find a url syntax for this). 

Maybe I'm missing something that already exists?

**Comment by abuchholtzau** [comment] 2020-06-22 17:23
Hey @paulgmiller, I think #51 is pretty similar to what you're asking here?
Let me know if you disagree, otherwise I'll close this one as a duplicate of that item :)

**Comment by paulgmiller** [comment] 2020-06-22 17:33
That's it. Thanks!

**Comment by abuchholtzau** [comment] 2020-06-22 18:00
Closing in favor of #51 😄

**Closed by abuchholtzau** 2020-06-22 18:00 UTC
