### ISSUE TITLE
Adding a folder to a new workspace breaks the entire instance

### ISSUE THREAD

**Issue by iansan5653** [MicrosoftDocs/vsonline#449] opened 2020-05-01 19:32 UTC
All I want to do is just open a single subfolder in a repository, rather than the entire repo. Here's what's happening:

1. I make a new instance. The only file open is the Readme
2. Clone the repository (doesn't matter if I use the Git extension or the command line)
3. Add a folder from that repository to the workspace.
4. The page reloads and now I can't add folders to the workspace or do anything else without an error popping up saying I don't have access to the workspace file.
5. I can use File -> Open Folder to open the folder, but then it creates an entirely new workspace. Every time I reopen the instance, I have to use link with the correct `?workspace=` parameter or it just takes me to a blank, unusable workspace. In addition, if I accidentally do go to the dashboard and open the workspace from there, all my extensions get deleted due to #448.

**Comment by jkeech** [comment] 2020-05-01 22:25
I can repro this. It looks like when you start with `Workspaces: Add Folder to Workspace` outside of the context of an existing workspace, it tries to create a brand new workspace file under `/Users/Workspaces`, such as `/Users/Workspaces/Untitled-1588371263001.code-workspace`. The problem is that this path does not exist, and it would require `root` access to write. The base image intentionally runs under a non-root user (`vsonline`), so it cannot write a file at that path.

I think the short-term solution is to first create a workspace file in the codespace default directory (e.g. `/home/vsonline/workspace`), which has full permissions for the executing user. You can do this by running `Workspaces: Save Workspace As...`, which will create the `.code-workspace` file in the correct directory. Then future modifications to the workspace (via `Workspaces: Add Folder to Workspace` or manually editing the file) will work.

We can also look at modifying the base image to either 1) include `/Users/Workspaces/` and give the executing account permission to write files there, or 2) Changing VS Code behavior for the default path to write the new workspace file to be inside the already opened folder.

**Comment by jkeech** [comment] 2020-05-01 23:35
Actually, it looks like this might be a bug in VS Code. The untitled workspaces are stored in user data which is in IndexedDB on the browser instead of on disk in the remote side. The workspace file contents is correctly saved. But after the reload into the workspace, VS Code seems to try to write updates to disk on the remote side (which fails) instead of back to the user data on the client side. cc @kieferrm

**Comment by bpasero** [comment] 2020-05-02 05:52
@jkeech you should sync with @legomushroom on this topic. Untitled workspace support is something VSO needs to adopt via supporting `URI` as paths for workspaces and should work fine once adopted. We will not write to any path on disk, everything will be in IndexDB, but as long as `URI` is not properly adopted, the location will be wrong.

**Comment by jkeech** [comment] 2020-05-02 05:54
@bpasero, thanks, I'll follow up with @legomushroom about how we are handling workspace paths.

**Comment by bpasero** [comment] 2020-05-02 05:55
@jkeech I should have made clear in my comment that I had lengthy discussions with Oleg on this topic, so he should be aware of what needs to be done. Last I spoke to him, this is something he wanted to move forward after GH Satellite.

**Comment by legomushroom** [comment] 2020-05-04 19:34
We have a PR in flight to fix this, the plan is to support both absolute paths and URIs but we need more testing to make sure or corner cases are covered.

**Comment by sebastianrogers** [comment] 2020-06-09 08:41
This is a real issue when combined with the limit of three instances per plan and two plans per subscription as it results in being only able to work on a very few projects at any one time.

**Comment by bpasero** [comment] 2020-06-09 08:51
From my testing I think this fix is in, @legomushroom can you confirm?

**Comment by sebastianrogers** [comment] 2020-06-10 06:34
Retested and I can make it work but its not intuitive:

- Create a VS Codespace
- Clone a first repository
- **Ctrl-Shft-P** *Workspaces: Save Workspace as...*
  - Save to *~/workspaces/[workspace name]*
- Clone a second repository
- Edit the *~/workspaces/[workspace name].code-workspace* file
- Add the path to the cloned second repository
- **Ctrl-Shft-P** *Workspaces: Open Workspace as...*
  - Open the *~/workspaces/[workspace name].code-workspace* workspace

The **Ctrl-Shft-P** *Add folder to workspace...* option just doesn't work.

Also any spaces in the folder name (can easily happen if using the **Ctrl-Shft-P** *Git: Clone* command means the default workspace will have spaces in its path which should be %20, cn be fixed directy in the file.

**Comment by sebastianrogers** [comment] 2020-06-13 12:33
- Create a new Codespace
  - No git repository
- Clone a Visual Studio DEVOPs repository - with a space in the title
- Open cloned repository
- Save Workspace As

- Clone a Visual Studio DEVOPs repository - with a space in the title
- Open cloned repository

- Open original workspace
- Add newly cloned repository

And it all works perfectly!

Things I have notoced.

- This was a brand new Codespace the original ones were about three weeks old.
- The Git Clone no longer transforms spaces into %20 so the Workspace folder paths and folder names now match up.

I'd say this is all working as expected.

Cheers

**Comment by legomushroom** [comment] 2020-06-14 06:27
@sebastianrogers great to hear it works, please let us know if you hit it again 😊

**Closed by legomushroom** 2020-06-14 06:27 UTC
Labels: area: web editor, bug, details-needed
