### ISSUE TITLE
“Find files” and tasks don’t work properly when opening a workspace file

### ISSUE THREAD

**Issue by ThomasNigro** [MicrosoftDocs/vsonline#327] opened 2020-03-03 12:20 UTC
Hello,

I extensively rely on Cmd + P to quickly go to a certain file - it currently doesn't work. Same goes for discovering my different tasks.json and launch.json files, so running a specific task doesn't work either.

When I search a file using Cmd P, I get a notification saying `ENOENT` for `spawn /home/vsonline/.vscode-remote/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node\_modules/vscode-ripgrep/bin/rg`.

I opened the OUTPUT console, in the "Log (Window)" tab, and it displays ...
```
[2020-03-03 13:13:02.413] [window] [error] spawn /home/vsonline/.vscode-remote/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node_modules/vscode-ripgrep/bin/rg ENOENT: Error: spawn /home/vsonline/.vscode-remote/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node_modules/vscode-ripgrep/bin/rg ENOENT
    at Object.t.deserializeSearchError (https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3847:111)
    at https://online.visualstudio.com/static/web-standalone/stable/out/vs/workbench/workbench.web.api.js:3887:134
```
... every time I try to run a task by searching for its name.

The issue seems to be not finding the file `/home/vsonline/.vscode-remote/bin/c47d83b293181d9be64f27ff093689e8e7aed054/node_modules/vscode-ripgrep/bin/rg`, however by manually navigating to it I can find it.

I've been able to reproduce the issue on two VS Online environments I have, using the VS Online instance running in Microsoft Edge (for MacOS) and in the native VS Code.

I'm launching a VS Code or VSOnline in Edge from a multi-folder Code workspace located inside the `~/workspace` folder.

**Comment by jkeech** [comment] 2020-03-06 00:15
I'm not able to reproduce this issue, although I don't have a macOS machine to test on. But it doesn't look like the client-side OS would be the issue based on the error. Can you give some more details about your environment? Are you using a `devcontainer.json` to customize the container in any way?

**Comment by lostintangent** [comment] 2020-03-21 17:58
@jkeech Did you try to repro this with a VS Code workspace file? I believe we’ve heard similar issues from other users, so I wonder if we have a problem with VS Code workspaces as opposed to just opening directories.

**Comment by jkeech** [comment] 2020-03-26 00:37
@lostintangent, I just tried this from within a multi-folder workspace and `Ctrl+p` to find and jump to files worked correctly. This was in Edge Dev on Windows, but I don't think that would make a difference.

**Comment by ThomasNigro** [comment] 2020-03-30 17:26
Hello everyone,

Not using a custom `devcontainer.json` file.

However I think I've managed to narrow down the issue.

Let's say I have a VS Code workspace which contains many repo: most of them are .NET projects, and one is a Unity3D project. I use this workspace on three setups:
1. On my office workstation, all the repos are cloned since this workstation has Unity installed on it. It works fine.
2. On my laptop, which doesn't have Unity installed.
3. On my VS Online instance which I use with VS Code, and therefore of course doesn't have Unity installed :)

Since I don't have Unity on my laptop, I generally avoid cloning the repo that needs Unity. I can open the VS Code workspace just fine, even if one workspace folder is missing.
I did the same on the VS Online instance: the repo that needs Unity is not cloned.
By adding a fake, empty folder with the appropriate name, discovering files and tasks started working. Which means the bug mentioned in the original post can be reproduced when one workspace folder is missing. It causes the whole file discovery to stop working.

My temporary "fix" is to just clone those repos that I won't use, but at least that way I can finally have my workspace working. And it is _awesome_. Congrats on VS Online!

**Comment by jkeech** [comment] 2020-03-30 17:32
> By adding a fake, empty folder with the appropriate name, discovering files and tasks started working. Which means the bug mentioned in the original post can be reproduced when one workspace folder is missing. It causes the whole file discovery to stop working.

@kieferrm, is this a known issue? It sounds like we might want to open a VS Code issue for this if not.

**Comment by kieferrm** [comment] 2020-04-01 15:07
Tracked in https://github.com/microsoft/vscode/issues/94170.

**Comment by jkeech** [comment] 2020-04-01 15:54
Closing this issue since it's being tracked in VS Code. VS Online will pick up the VS Code update once it's available.

**Closed by jkeech** 2020-04-01 15:54 UTC
Labels: area: vscode, area: web editor, area:customization, bug
