### ISSUE TITLE
VSO ignores Dockerfile

### ISSUE THREAD

**Issue by bergmeister** [MicrosoftDocs/vsonline#229] opened 2019-11-30 10:34 UTC
Try create an environment using this repo and `master` branch: https://github.com/PowerShell/PowerShell

The `.devcontainer\devcontainer.json` file has the property `"dockerFile": "Dockerfile"`, which points to the [DockerFile](https://github.com/PowerShell/PowerShell/blob/master/.devcontainer/Dockerfile) in the `.devcontainer` folder
https://github.com/PowerShell/PowerShell/blob/d68d126cae263637a819a14f83062d63a6f221b0/.devcontainer/devcontainer.json#L4

However, VSO, seems to ignore the Docker file as the docker file contains the .net core 3.1-preview3, but executing `dotnet --version` clearly shows that the Dockerfile is not being used as this .Net SDK is not there.

Related to #15 ?

**Comment by lostintangent** [comment] 2019-11-30 21:13
Hey! Yeah this is a duplicate of #15. We’ll be shipping support for custom Docker files/images very soon, and will report progress on #15 👍

**Closed by lostintangent** 2019-11-30 21:13 UTC

**Comment by bergmeister** [comment] 2019-11-30 22:25
Ok, thanks for the info, but the docs are very misleading as it sounds like it's already supported or do I misunderstand something?
https://docs.microsoft.com/en-us/visualstudio/online/reference/configuring#visual-studio-online-configuration-reference
