### ISSUE TITLE
Unable to create environment from Azure DevOps Repo

### ISSUE THREAD

**Issue by chrisjgell** [MicrosoftDocs/vsonline#218] opened 2019-11-25 16:55 UTC
When creating a new environment via the web app, I am unable to create an environment using a private Azure DevOps repo URL. When attempting I get an error "We are unable to clone this repository automatically"

**Comment by nikmd23** [comment] 2019-11-25 20:09
Hi @chrisjgell!

I'm going to close this issues as a dupe of #48. Do take a look at that thread though, as there's a work around suggested there you may be able to use.

**Closed by nikmd23** 2019-11-25 20:09 UTC
