### ISSUE TITLE
Failed to start VS Code Remote server

### ISSUE THREAD

**Issue by mjbvz** [MicrosoftDocs/vsonline#22] opened 2019-11-01 02:33 UTC
1. Using the current production deployment.
1. After reloading the window for my environment multiple times, on one reload the workbench was unable to load. I saw the following errors in the chrome developer tools:

```
workbench.web.api.js:formatted:63344   ERR Failed to start VS Code Remote server.: Error: Failed to start VS Code Remote server.
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55456
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55774
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:56141
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776204
    at l (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776314)
    at n (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:775264)
workbench.web.api.js:formatted:63344   ERR [remote-connection][ExtensionHost][2e043…][initial][localhost:80] socketFactory.connect() failed. Error:
workbench.web.api.js:formatted:63344   ERR Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
workbench.web.api.js:formatted:63344   ERR [remote-connection][Management   ][6c649…][initial][localhost:80] socketFactory.connect() failed. Error:
workbench.web.api.js:formatted:63344   ERR Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
workbench.web.api.js:formatted:63344   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
workbench.web.api.js:formatted:63344   ERR Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
workbench.web.api.js:formatted:63344   ERR [remote-connection] An error occurred in the very first connect attempt, it will be treated as a permanent error! Error:
workbench.web.api.js:formatted:63344   ERR Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
workbench.web.api.js:formatted:140616 Error received from starting extension host
(anonymous) @ workbench.web.api.js:formatted:140616
Promise.then (async)
e @ workbench.web.api.js:formatted:140614
_createInstance @ workbench.web.api.js:formatted:62722
createInstance @ workbench.web.api.js:formatted:62703
_createExtensionHosts @ workbench.web.api.js:formatted:160196
_startExtensionHostProcess @ workbench.web.api.js:formatted:135683
_initialize @ workbench.web.api.js:formatted:135656
D @ workbench.web.api.js:formatted:160166
_createInstance @ workbench.web.api.js:formatted:62722
_createServiceInstance @ workbench.web.api.js:formatted:62808
_createServiceInstanceWithOwner @ workbench.web.api.js:formatted:62786
_createAndCacheServiceInstance @ workbench.web.api.js:formatted:62777
_getOrCreateServiceInstance @ workbench.web.api.js:formatted:62739
get @ workbench.web.api.js:formatted:62687
initLayout @ workbench.web.api.js:formatted:207533
(anonymous) @ workbench.web.api.js:formatted:208184
invokeFunction @ workbench.web.api.js:formatted:62693
startup @ workbench.web.api.js:formatted:208180
open @ workbench.web.api.js:formatted:208387
async function (async)
open @ workbench.web.api.js:formatted:208380
t.main @ workbench.web.api.js:formatted:208539
t.create @ workbench.web.api.js:formatted:225130
(anonymous) @ workbench.tsx:173
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ workbench.tsx:173
value @ workbench.tsx:68
Wa @ react-dom.production.min.js:4980
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ds @ react-dom.production.min.js:5992
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
o.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
g @ redux.js:220
(anonymous) @ configureStore.ts:35
(anonymous) @ middleware.ts:59
value @ useActionContext.ts:60
(anonymous) @ useDispatch.ts:43
(anonymous) @ fetchEnvironments.ts:32
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
b @ fetchEnvironments.ts:26
v @ fetchEnvironments.ts:26
(anonymous) @ init.ts:46
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
k @ init.ts:19
y @ init.ts:19
(anonymous) @ redux.js:476
(anonymous) @ app.tsx:31
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ app.tsx:31
Wa @ react-dom.production.min.js:4978
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
xs @ react-dom.production.min.js:5860
Ja @ react-dom.production.min.js:5787
Ls @ react-dom.production.min.js:6077
Bs @ react-dom.production.min.js:6085
zs.render @ react-dom.production.min.js:6276
(anonymous) @ react-dom.production.min.js:6360
Rs @ react-dom.production.min.js:6007
Hs @ react-dom.production.min.js:6359
render @ react-dom.production.min.js:6390
(anonymous) @ index.tsx:30
476 @ index.tsx:40
f @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
a @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
e @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
(anonymous) @ main.310c24d4.chunk.js:1
Show 38 more frames
workbench.web.api.js:formatted:140617 Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
(anonymous) @ workbench.web.api.js:formatted:140617
Promise.then (async)
e @ workbench.web.api.js:formatted:140614
_createInstance @ workbench.web.api.js:formatted:62722
createInstance @ workbench.web.api.js:formatted:62703
_createExtensionHosts @ workbench.web.api.js:formatted:160196
_startExtensionHostProcess @ workbench.web.api.js:formatted:135683
_initialize @ workbench.web.api.js:formatted:135656
D @ workbench.web.api.js:formatted:160166
_createInstance @ workbench.web.api.js:formatted:62722
_createServiceInstance @ workbench.web.api.js:formatted:62808
_createServiceInstanceWithOwner @ workbench.web.api.js:formatted:62786
_createAndCacheServiceInstance @ workbench.web.api.js:formatted:62777
_getOrCreateServiceInstance @ workbench.web.api.js:formatted:62739
get @ workbench.web.api.js:formatted:62687
initLayout @ workbench.web.api.js:formatted:207533
(anonymous) @ workbench.web.api.js:formatted:208184
invokeFunction @ workbench.web.api.js:formatted:62693
startup @ workbench.web.api.js:formatted:208180
open @ workbench.web.api.js:formatted:208387
async function (async)
open @ workbench.web.api.js:formatted:208380
t.main @ workbench.web.api.js:formatted:208539
t.create @ workbench.web.api.js:formatted:225130
(anonymous) @ workbench.tsx:173
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ workbench.tsx:173
value @ workbench.tsx:68
Wa @ react-dom.production.min.js:4980
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ds @ react-dom.production.min.js:5992
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
o.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
g @ redux.js:220
(anonymous) @ configureStore.ts:35
(anonymous) @ middleware.ts:59
value @ useActionContext.ts:60
(anonymous) @ useDispatch.ts:43
(anonymous) @ fetchEnvironments.ts:32
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
b @ fetchEnvironments.ts:26
v @ fetchEnvironments.ts:26
(anonymous) @ init.ts:46
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
k @ init.ts:19
y @ init.ts:19
(anonymous) @ redux.js:476
(anonymous) @ app.tsx:31
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ app.tsx:31
Wa @ react-dom.production.min.js:4978
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
xs @ react-dom.production.min.js:5860
Ja @ react-dom.production.min.js:5787
Ls @ react-dom.production.min.js:6077
Bs @ react-dom.production.min.js:6085
zs.render @ react-dom.production.min.js:6276
(anonymous) @ react-dom.production.min.js:6360
Rs @ react-dom.production.min.js:6007
Hs @ react-dom.production.min.js:6359
render @ react-dom.production.min.js:6390
(anonymous) @ index.tsx:30
476 @ index.tsx:40
f @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
a @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
e @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
(anonymous) @ main.310c24d4.chunk.js:1
Show 38 more frames
workbench.web.api.js:formatted:63344   ERR Error: Failed to start VS Code Remote server.
    at main.js:531
    at main.js:355
    at main.js:338
    at setImmediate.js:48
    at l (setImmediate.js:83)
    at n (setImmediate.js:125)
workbench.web.api.js:formatted:104253 Failed to connect to the remote extension host server (Error: Failed to start VS Code Remote server.)
onDidNotificationChange @ workbench.web.api.js:formatted:104253
(anonymous) @ workbench.web.api.js:formatted:104249
fire @ workbench.web.api.js:formatted:4904
addNotification @ workbench.web.api.js:formatted:106844
error @ workbench.web.api.js:formatted:151648
(anonymous) @ workbench.web.api.js:formatted:160372
Promise.then (async)
b @ workbench.web.api.js:formatted:160371
_createInstance @ workbench.web.api.js:formatted:62722
createInstance @ workbench.web.api.js:formatted:62703
safeCreateInstance @ workbench.web.api.js:formatted:105608
doInstantiateByPhase @ workbench.web.api.js:formatted:105588
instantiateByPhase @ workbench.web.api.js:formatted:105580
(anonymous) @ workbench.web.api.js:formatted:105575
start @ workbench.web.api.js:formatted:105574
startRegistries @ workbench.web.api.js:formatted:208224
(anonymous) @ workbench.web.api.js:formatted:208185
invokeFunction @ workbench.web.api.js:formatted:62693
startup @ workbench.web.api.js:formatted:208180
open @ workbench.web.api.js:formatted:208387
async function (async)
open @ workbench.web.api.js:formatted:208380
t.main @ workbench.web.api.js:formatted:208539
t.create @ workbench.web.api.js:formatted:225130
(anonymous) @ workbench.tsx:173
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ workbench.tsx:173
value @ workbench.tsx:68
Wa @ react-dom.production.min.js:4980
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ds @ react-dom.production.min.js:5992
notify @ Subscription.js:23
t.notifyNestedSubs @ Subscription.js:65
o.notifySubscribers @ Provider.js:59
t.handleChangeWrapper @ Subscription.js:70
g @ redux.js:220
(anonymous) @ configureStore.ts:35
(anonymous) @ middleware.ts:59
value @ useActionContext.ts:60
(anonymous) @ useDispatch.ts:43
(anonymous) @ fetchEnvironments.ts:32
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
b @ fetchEnvironments.ts:26
v @ fetchEnvironments.ts:26
(anonymous) @ init.ts:46
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
k @ init.ts:19
y @ init.ts:19
(anonymous) @ redux.js:476
(anonymous) @ app.tsx:31
_ @ runtime.js:63
(anonymous) @ runtime.js:282
e.<computed> @ runtime.js:116
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ app.tsx:31
Wa @ react-dom.production.min.js:4978
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Os @ react-dom.production.min.js:5974
Ps @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
xs @ react-dom.production.min.js:5860
Ja @ react-dom.production.min.js:5787
Ls @ react-dom.production.min.js:6077
Bs @ react-dom.production.min.js:6085
zs.render @ react-dom.production.min.js:6276
(anonymous) @ react-dom.production.min.js:6360
Rs @ react-dom.production.min.js:6007
Hs @ react-dom.production.min.js:6359
render @ react-dom.production.min.js:6390
(anonymous) @ index.tsx:30
476 @ index.tsx:40
f @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
a @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
e @ 63c0b6cd-f25d-4e16-a92a-1d241bdc7c4b:24
(anonymous) @ main.310c24d4.chunk.js:1
Show 38 more frames
workbench.web.api.js:formatted:63344   ERR Failed to start VS Code Remote server.: Error: Failed to start VS Code Remote server.
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55456
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55774
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:56141
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776204
    at l (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776314)
    at n (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:775264)
workbench.web.api.js:formatted:63344   ERR Could not fetch environment: Error: Could not fetch environment
    at https://online.visualstudio.com/static/web-standalone/out/vs/workbench/workbench.web.api.js:3959:325
workbench.web.api.js:formatted:63344   ERR Failed to start VS Code Remote server.: Error: Failed to start VS Code Remote server.
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55456
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55774
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:56141
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776204
    at l (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776314)
    at n (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:775264)
workbench.web.api.js:formatted:185349 No search provider registered for scheme: vscode-remote
(anonymous) @ workbench.web.api.js:formatted:185349
searchWithProviders @ workbench.web.api.js:formatted:185339
(anonymous) @ workbench.web.api.js:formatted:185306
Promise.then (async)
doSearch @ workbench.web.api.js:formatted:185303
fileSearch @ workbench.web.api.js:formatted:185295
(anonymous) @ workbench.web.api.js:formatted:179192
load @ workbench.web.api.js:formatted:179262
onOpen @ workbench.web.api.js:formatted:179193
onOpen @ workbench.web.api.js:formatted:179409
(anonymous) @ workbench.web.api.js:formatted:167212
Promise.then (async)
resolveHandler @ workbench.web.api.js:formatted:167211
show @ workbench.web.api.js:formatted:166952
handler @ workbench.web.api.js:formatted:104797
e.handler @ workbench.web.api.js:formatted:61351
invokeFunction @ workbench.web.api.js:formatted:62693
_tryExecuteCommand @ workbench.web.api.js:formatted:128939
executeCommand @ workbench.web.api.js:formatted:128923
_doDispatch @ workbench.web.api.js:formatted:62972
_dispatch @ workbench.web.api.js:formatted:62950
(anonymous) @ workbench.web.api.js:formatted:143457
7workbench.web.api.js:formatted:63344   ERR Failed to start VS Code Remote server.: Error: Failed to start VS Code Remote server.
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55456
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:55774
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:56141
    at https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776204
    at l (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:776314)
    at n (https://online.visualstudio.com/static/js/2.0759df4e.chunk.js:1:775264)
```

This was for a fairly new environment and after reloading again I was able to connect

(sorry I don't have actual repo steps and cannot reliably hit this)

/cc @kieferrm

**Comment by jkeech** [comment] 2019-12-05 20:23
Closing since we haven't been able to reproduce this. Please re-open if you continue to see this error. Thanks!

**Closed by jkeech** 2019-12-05 20:23 UTC
Labels: bug

**Comment by ckuehnel89** [comment] 2019-12-27 21:37
I have been having this issue for over 2 weeks now at work and never had any success. I tested at home and it worked once and then that also started doing the same thing. 'Failed to start VS Code Remote server' is the error I always get when connecting either from the browser or from VS Code client. Self hosted environment creates successfully without issue and shows "Available" on the website when viewing environments.

**Comment by jkeech** [comment] 2019-12-27 21:58
@ckuehnel89, You are probably hitting a different issue with self-hosted environments (such as #14 or #5). The status currently doesn't report correctly for self-hosted; it will always show "Available". Can you try running the command to re-register the self-hosted environment, and if that doesn't work, please open a new issue for tracking.

**Comment by ckuehnel89** [comment] 2019-12-27 22:07
@jkeech Thank you for your quick reply. So at work, the self-hosted environment has never worked, not once so not sure that #14 would be the case and #5 pertains to rebooting the pc and then having to restore the environment which I have not rebooted the pc. Tested on a Windows 10 PC as well as a Server 2012 R2 PC both with the same results. I DMZ'd the Server 2012 and disabled Windows Firewall with no change, I enabled sharing on the folder for the workspace as well. I also created a new billing plan in a different region in Azure and no difference, same error when trying to connect.

**Comment by ckuehnel89** [comment] 2019-12-27 22:18
`Failed to connect to the remote extension host server (Error: Failed to start VS Code Remote server.)` and then followed by `Resolving the authority 'vsonline' failed` are the two errors I get.

I see that in my Resource Monitor under Network tab, vsls-agent.exe is running and shows active TCP connections using Remote port 443 (https) and when I attempt to connect to the server environment from a client (either from the browser or from another instance of VS Code), more TCP connections show up as if it is receiving the incoming connections yet they are failing to connect to it. I also ensured that my workspace directory has no spaces or hyphens or dashes.

**Comment by ckuehnel89** [comment] 2019-12-27 23:55
Problem solved, for anyone else that keeps getting this error, don't use Windows lol. I setup VS Code on CentOS 8 and got it working first try with browser and with client VS Code. Appears to be a TCP issue of sorts. When connecting to a Windows server environment, I would never even get a firewall pop up alert on client to allow the connection, the moment I connected to the CentOS 8 server environment, pop up came up asking to allow the connection in Windows Firewall, I accepted and poof, I can see all the code.

**Comment by jkeech** [comment] 2019-12-28 00:07
@ckuehnel89, please open a new issue to track separately. In the Windows case, you might be hitting the initial timeout while the VS Code remote server is being unzipped (currently takes ~1 minute to unzip the server on Windows while VS Code has a 20 second timeout, so the first connection which causes the server to be downloaded and cached almost always fails). #87 is tracking the fix for that.
