### ISSUE TITLE
disable auto shutdown of self-hosted environments

### ISSUE THREAD

**Issue by OneCyrus** [MicrosoftDocs/vsonline#249] opened 2019-12-08 09:42 UTC
is there a way to disable this auto-shutdown? after th3e shutdown I can't reconnect from remote and need to login to the system and use "restore local environment".

```
[03:43:30] Last EH closed, waiting before shutting down
[03:43:40] [127.0.0.1][36173ab2][ManagementConnection] The reconnection grace time of 3h has expired, so the connection will be disposed.
Last EH closed, shutting down
```

in the long term it would be very nice to have something like a lightweight agent which listens to connections and auto-starts the full experience when connecting from remote.

**Comment by jkeech** [comment] 2019-12-09 20:40
@OneCyrus, the VS Code server process will shutdown after the [timeout](https://github.com/microsoft/vscode/blob/abbf52b1378e2976803f81b1317fe3a5e6e39c23/src/vs/workbench/services/extensions/node/extensionHostProcessSetup.ts#L108), but the VSO agent should continue to run. As long as the VSO agent is running and connected, you should be able to establish a connection to the environment. As part of connection, the VSO agent will attempt to re-use an existing VS Code server process if a matching one is found, and if not, it will create a new one. I believe this is what you are suggesting the behavior should be.

We do currently have a limitation that the VSO agent process is not installed as a service, so if the process dies, you need to restore the environment to get it running again. But we are working on getting the VSO agent to be installed as a service so it can survive reboots/crashes (#5).

**Comment by jkeech** [comment] 2020-01-16 18:45
Closing as a duplicate of #5

**Closed by jkeech** 2020-01-16 18:45 UTC
Labels: area: self-hosting
